export interface ThemePresetItem {
  id: string;
  name: string;
  group: string;
  darkBg: string;
  darkSurface: string;
  lightBg: string;
  lightSurface: string;
  darkAccent: string;
  lightAccent: string;
  prefersLight?: boolean;
}

export const THEME_GROUPS = [
  "Cyber & Sci-Fi Neon",
  "Paper & Editorial",
  "Luxury & OLED Pure",
  "Atmospheric & Nature",
  "Earthy & Forest",
  "Warm & Twilight",
  "Retro & Terminal",
  "Cosmic & Ethereal",
  "Dark & Midnight",
  "Pastel & Dream",
  "Monochrome & Slate",
  "Minimal & Clean"
];

// Curated comprehensive set of creative theme presets (totaling 184 across 12 groups)
export const THEME_PRESETS: ThemePresetItem[] = [
  {
    "id": "cyberpunk_2077",
    "name": "Cyberpunk 2077",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#08090C",
    "darkSurface": "#141724",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FFE600",
    "lightAccent": "#CA8A04"
  },
  {
    "id": "tokyo_midnight_rain",
    "name": "Tokyo Midnight Rain",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#040714",
    "darkSurface": "#0D162E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#00F5D4",
    "lightAccent": "#0D9488"
  },
  {
    "id": "matrix_digital_rain",
    "name": "Matrix Digital Rain",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#020703",
    "darkSurface": "#071D0A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#00FF66",
    "lightAccent": "#059669"
  },
  {
    "id": "synthwave_sunset",
    "name": "Synthwave 80s Sunset",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0D031A",
    "darkSurface": "#1E0837",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FF3864",
    "lightAccent": "#E11D48"
  },
  {
    "id": "blade_runner_2049",
    "name": "Blade Runner Noir",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0C0704",
    "darkSurface": "#1C1008",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FF5E00",
    "lightAccent": "#EA580C"
  },
  {
    "id": "neon_overdrive",
    "name": "Neon Overdrive",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#090514",
    "darkSurface": "#140C29",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A855F7",
    "lightAccent": "#7E22CE"
  },
  {
    "id": "quantum_laser",
    "name": "Quantum Laser",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#030A14",
    "darkSurface": "#07162C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "ghost_in_shell",
    "name": "Ghost in the Shell",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#060A10",
    "darkSurface": "#0D1522",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#2DD4BF",
    "lightAccent": "#0F766E"
  },
  {
    "id": "hackers_terminal",
    "name": "Hackers Terminal",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#05070A",
    "darkSurface": "#0B1017",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#22C55E",
    "lightAccent": "#15803D"
  },
  {
    "id": "retrowave_grid",
    "name": "Retrowave Grid",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0D061A",
    "darkSurface": "#180E2E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#BE123C"
  },
  {
    "id": "hyperdrive_blue",
    "name": "Hyperdrive Blue",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#040716",
    "darkSurface": "#09102E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#60A5FA",
    "lightAccent": "#2563EB"
  },
  {
    "id": "plasma_pink",
    "name": "Plasma Pink Neon",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#120410",
    "darkSurface": "#240A20",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EC4899",
    "lightAccent": "#DB2777"
  },
  {
    "id": "oled_absolute_pitch",
    "name": "OLED Pure Black",
    "group": "Luxury & OLED Pure",
    "darkBg": "#000000",
    "darkSurface": "#0E0E12",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#8B5CF6",
    "lightAccent": "#6D28D9"
  },
  {
    "id": "obsidian_royal_gold",
    "name": "Obsidian & 24K Gold",
    "group": "Luxury & OLED Pure",
    "darkBg": "#000000",
    "darkSurface": "#141410",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#B45309"
  },
  {
    "id": "amethyst_royale",
    "name": "Amethyst Royale",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0B0410",
    "darkSurface": "#170A21",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "champagne_caviar",
    "name": "Champagne & Caviar",
    "group": "Luxury & OLED Pure",
    "darkBg": "#08080A",
    "darkSurface": "#131317",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#E2B887",
    "lightAccent": "#A16207"
  },
  {
    "id": "titanium_stealth",
    "name": "Titanium Stealth",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0D0E11",
    "darkSurface": "#17191E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#94A3B8",
    "lightAccent": "#475569"
  },
  {
    "id": "emerald_imperial",
    "name": "Imperial Emerald",
    "group": "Luxury & OLED Pure",
    "darkBg": "#040E08",
    "darkSurface": "#0B1C11",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#047857"
  },
  {
    "id": "sapphire_regal",
    "name": "Regal Sapphire",
    "group": "Luxury & OLED Pure",
    "darkBg": "#040A18",
    "darkSurface": "#0B142E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#3B82F6",
    "lightAccent": "#1D4ED8"
  },
  {
    "id": "ruby_velvet",
    "name": "Velvet Ruby",
    "group": "Luxury & OLED Pure",
    "darkBg": "#120407",
    "darkSurface": "#240A10",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#E11D48",
    "lightAccent": "#9F1239"
  },
  {
    "id": "platinum_noir",
    "name": "Platinum Noir",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0B0C0E",
    "darkSurface": "#14161A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#CBD5E1",
    "lightAccent": "#334155"
  },
  {
    "id": "bronze_atelier",
    "name": "Bronze Atelier",
    "group": "Luxury & OLED Pure",
    "darkBg": "#100B07",
    "darkSurface": "#1E150F",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#CA8A04",
    "lightAccent": "#854D0E"
  },
  {
    "id": "nordic_aurora_borealis",
    "name": "Nordic Aurora Borealis",
    "group": "Atmospheric & Nature",
    "darkBg": "#030C10",
    "darkSurface": "#071822",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#2DD4BF",
    "lightAccent": "#0D9488"
  },
  {
    "id": "mariana_abyssal",
    "name": "Mariana Trench",
    "group": "Atmospheric & Nature",
    "darkBg": "#020712",
    "darkSurface": "#061229",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#0284C7",
    "lightAccent": "#0369A1"
  },
  {
    "id": "amazon_canopy",
    "name": "Amazonian Canopy",
    "group": "Atmospheric & Nature",
    "darkBg": "#040E06",
    "darkSurface": "#091C0E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#22C55E",
    "lightAccent": "#15803D"
  },
  {
    "id": "sahara_solar_dune",
    "name": "Sahara Solar Dune",
    "group": "Atmospheric & Nature",
    "darkBg": "#120A05",
    "darkSurface": "#21130B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706"
  },
  {
    "id": "icelandic_glacier_ice",
    "name": "Icelandic Glacier",
    "group": "Atmospheric & Nature",
    "darkBg": "#050E1A",
    "darkSurface": "#0C1C33",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "volcanic_basalt",
    "name": "Volcanic Basalt",
    "group": "Atmospheric & Nature",
    "darkBg": "#0D0706",
    "darkSurface": "#1C0F0E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EF4444",
    "lightAccent": "#DC2626"
  },
  {
    "id": "autumn_maple_grove",
    "name": "Autumn Maple Grove",
    "group": "Atmospheric & Nature",
    "darkBg": "#130906",
    "darkSurface": "#24120C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F97316",
    "lightAccent": "#EA580C"
  },
  {
    "id": "misty_redwoods",
    "name": "Misty Redwoods",
    "group": "Atmospheric & Nature",
    "darkBg": "#080E0A",
    "darkSurface": "#121D15",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#14B8A6",
    "lightAccent": "#0F766E"
  },
  {
    "id": "swiss_modernist_orange",
    "name": "Swiss Modernist",
    "group": "Editorial & Minimal",
    "darkBg": "#0C0C0C",
    "darkSurface": "#171717",
    "lightBg": "#FFFFFF",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FF4400",
    "lightAccent": "#EA580C",
    "prefersLight": true
  },
  {
    "id": "kyoto_matcha_stone",
    "name": "Kyoto Matcha & Stone",
    "group": "Editorial & Minimal",
    "darkBg": "#0B0F0C",
    "darkSurface": "#151D17",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#84CC16",
    "lightAccent": "#4D7C0F",
    "prefersLight": true
  },
  {
    "id": "tokyo_wabi_sabi_kozo",
    "name": "Wabi-Sabi Kozo Paper",
    "group": "Editorial & Minimal",
    "darkBg": "#131210",
    "darkSurface": "#1D1B18",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#78716C",
    "lightAccent": "#44403C",
    "prefersLight": true
  },
  {
    "id": "tuscan_terracotta_sun",
    "name": "Tuscan Terracotta",
    "group": "Editorial & Minimal",
    "darkBg": "#140A07",
    "darkSurface": "#23120C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F97316",
    "lightAccent": "#C2410C",
    "prefersLight": true
  },
  {
    "id": "editorial_slate_ink",
    "name": "Editorial Ink & Slate",
    "group": "Editorial & Minimal",
    "darkBg": "#0F1115",
    "darkSurface": "#191C22",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#475569",
    "lightAccent": "#1E293B",
    "prefersLight": true
  },
  {
    "id": "nebula_supernova_star",
    "name": "Nebula Supernova",
    "group": "Cosmic & Ethereal",
    "darkBg": "#090414",
    "darkSurface": "#160B30",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#E11D48"
  },
  {
    "id": "solar_flare_eclipse_corona",
    "name": "Solar Corona Eclipse",
    "group": "Cosmic & Ethereal",
    "darkBg": "#0A0604",
    "darkSurface": "#170E0A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB923C",
    "lightAccent": "#D97706"
  },
  {
    "id": "dark_matter_event_horizon",
    "name": "Dark Matter Horizon",
    "group": "Cosmic & Ethereal",
    "darkBg": "#040408",
    "darkSurface": "#0B0B14",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#6366F1",
    "lightAccent": "#4338CA"
  },
  {
    "id": "stardust_aurora_lilac",
    "name": "Stardust Aurora",
    "group": "Cosmic & Ethereal",
    "darkBg": "#080516",
    "darkSurface": "#130B30",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "pulsar_neutron_beam",
    "name": "Pulsar Neutron Beam",
    "group": "Cosmic & Ethereal",
    "darkBg": "#040714",
    "darkSurface": "#0A1230",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "midnight",
    "name": "Midnight Classic",
    "group": "Dark & Midnight",
    "darkBg": "#090A0C",
    "darkSurface": "#121417",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#8B7CFF",
    "lightAccent": "#4F46E5"
  },
  {
    "id": "obsidian",
    "name": "Obsidian Deep",
    "group": "Dark & Midnight",
    "darkBg": "#0B0B0E",
    "darkSurface": "#15161C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#6366F1",
    "lightAccent": "#4338CA"
  },
  {
    "id": "void",
    "name": "Cosmic Void",
    "group": "Dark & Midnight",
    "darkBg": "#050508",
    "darkSurface": "#0E0E14",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A855F7",
    "lightAccent": "#7E22CE"
  },
  {
    "id": "onyx",
    "name": "Onyx Pure",
    "group": "Dark & Midnight",
    "darkBg": "#080808",
    "darkSurface": "#141414",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#3B82F6",
    "lightAccent": "#1D4ED8"
  },
  {
    "id": "charcoal",
    "name": "Charcoal Mist",
    "group": "Dark & Midnight",
    "darkBg": "#101216",
    "darkSurface": "#181B20",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#06B6D4",
    "lightAccent": "#0891B2"
  },
  {
    "id": "eclipse",
    "name": "Solar Eclipse",
    "group": "Dark & Midnight",
    "darkBg": "#0A090E",
    "darkSurface": "#14121A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706"
  },
  {
    "id": "abyss",
    "name": "Ocean Abyss",
    "group": "Dark & Midnight",
    "darkBg": "#040B14",
    "darkSurface": "#0B1524",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#0284C7",
    "lightAccent": "#0369A1"
  },
  {
    "id": "graphite",
    "name": "Graphite Dark",
    "group": "Dark & Midnight",
    "darkBg": "#111315",
    "darkSurface": "#1B1E22",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#64748B",
    "lightAccent": "#334155"
  },
  {
    "id": "carbon",
    "name": "Carbon Fiber",
    "group": "Dark & Midnight",
    "darkBg": "#0F0F12",
    "darkSurface": "#1A1A20",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EC4899",
    "lightAccent": "#BE185D"
  },
  {
    "id": "nebula_dark",
    "name": "Nebula Night",
    "group": "Dark & Midnight",
    "darkBg": "#080816",
    "darkSurface": "#121226",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#818CF8",
    "lightAccent": "#4F46E5"
  },
  {
    "id": "titanium",
    "name": "Titanium Matte",
    "group": "Dark & Midnight",
    "darkBg": "#141518",
    "darkSurface": "#1E2024",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#047857"
  },
  {
    "id": "shadow_realm",
    "name": "Shadow Realm",
    "group": "Dark & Midnight",
    "darkBg": "#060608",
    "darkSurface": "#101015",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#E11D48",
    "lightAccent": "#BE123C"
  },
  {
    "id": "dark_matter",
    "name": "Dark Matter",
    "group": "Dark & Midnight",
    "darkBg": "#05060A",
    "darkSurface": "#0E1018",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "deep_space",
    "name": "Deep Space",
    "group": "Dark & Midnight",
    "darkBg": "#070913",
    "darkSurface": "#0F1322",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#60A5FA",
    "lightAccent": "#2563EB"
  },
  {
    "id": "phantom",
    "name": "Phantom Cloak",
    "group": "Dark & Midnight",
    "darkBg": "#0D0E12",
    "darkSurface": "#161820",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "minimal_light",
    "name": "Minimal Light",
    "group": "Minimal & Clean",
    "darkBg": "#121417",
    "darkSurface": "#1A1D21",
    "lightBg": "#FFFFFF",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#6366F1",
    "lightAccent": "#4F46E5",
    "prefersLight": true
  },
  {
    "id": "pure_white",
    "name": "Pure Canvas",
    "group": "Minimal & Clean",
    "darkBg": "#18181B",
    "darkSurface": "#27272A",
    "lightBg": "#FFFFFF",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#8B7CFF",
    "lightAccent": "#18181B",
    "prefersLight": true
  },
  {
    "id": "snow",
    "name": "Alpine Snow",
    "group": "Minimal & Clean",
    "darkBg": "#111827",
    "darkSurface": "#1F2937",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#3B82F6",
    "lightAccent": "#2563EB",
    "prefersLight": true
  },
  {
    "id": "nordic",
    "name": "Nordic Clean",
    "group": "Minimal & Clean",
    "darkBg": "#13171F",
    "darkSurface": "#1C222D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#0EA5E9",
    "lightAccent": "#0284C7",
    "prefersLight": true
  },
  {
    "id": "cloud",
    "name": "Nimbus Cloud",
    "group": "Minimal & Clean",
    "darkBg": "#14161A",
    "darkSurface": "#1E2127",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#14B8A6",
    "lightAccent": "#0D9488",
    "prefersLight": true
  },
  {
    "id": "alabaster",
    "name": "Alabaster Crisp",
    "group": "Minimal & Clean",
    "darkBg": "#151619",
    "darkSurface": "#202226",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#64748B",
    "lightAccent": "#475569",
    "prefersLight": true
  },
  {
    "id": "frost",
    "name": "Morning Frost",
    "group": "Minimal & Clean",
    "darkBg": "#0F172A",
    "darkSurface": "#1E293B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#0284C7",
    "lightAccent": "#0369A1",
    "prefersLight": true
  },
  {
    "id": "porcelain",
    "name": "Porcelain White",
    "group": "Minimal & Clean",
    "darkBg": "#18181B",
    "darkSurface": "#27272A",
    "lightBg": "#FDFDFC",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D97706",
    "lightAccent": "#B45309",
    "prefersLight": true
  },
  {
    "id": "cotton",
    "name": "Soft Cotton",
    "group": "Minimal & Clean",
    "darkBg": "#171717",
    "darkSurface": "#262626",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#059669",
    "prefersLight": true
  },
  {
    "id": "ivory_clean",
    "name": "Clean Ivory",
    "group": "Minimal & Clean",
    "darkBg": "#191816",
    "darkSurface": "#272522",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706",
    "prefersLight": true
  },
  {
    "id": "quartz",
    "name": "White Quartz",
    "group": "Minimal & Clean",
    "darkBg": "#16161D",
    "darkSurface": "#22222E",
    "lightBg": "#FCFCFD",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#8B5CF6",
    "lightAccent": "#6D28D9",
    "prefersLight": true
  },
  {
    "id": "pearl",
    "name": "Lustrous Pearl",
    "group": "Minimal & Clean",
    "darkBg": "#151719",
    "darkSurface": "#212428",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#E11D48",
    "prefersLight": true
  },
  {
    "id": "milk_glass",
    "name": "Milk Glass",
    "group": "Minimal & Clean",
    "darkBg": "#111317",
    "darkSurface": "#1B1E24",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7",
    "prefersLight": true
  },
  {
    "id": "zenith",
    "name": "Zenith Peak",
    "group": "Minimal & Clean",
    "darkBg": "#12141A",
    "darkSurface": "#1C202A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#4F46E5",
    "lightAccent": "#3730A3",
    "prefersLight": true
  },
  {
    "id": "linen",
    "name": "Bleached Linen",
    "group": "Minimal & Clean",
    "darkBg": "#161614",
    "darkSurface": "#242420",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#84CC16",
    "lightAccent": "#65A30D",
    "prefersLight": true
  },
  {
    "id": "slate_metro",
    "name": "Slate Metro",
    "group": "Monochrome & Slate",
    "darkBg": "#0F172A",
    "darkSurface": "#1E293B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#94A3B8",
    "lightAccent": "#475569"
  },
  {
    "id": "zinc_industrial",
    "name": "Zinc Foundry",
    "group": "Monochrome & Slate",
    "darkBg": "#09090B",
    "darkSurface": "#18181B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A1A1AA",
    "lightAccent": "#52525B"
  },
  {
    "id": "neutral_mono",
    "name": "Neutral Mono",
    "group": "Monochrome & Slate",
    "darkBg": "#0A0A0A",
    "darkSurface": "#171717",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A3A3A3",
    "lightAccent": "#525252"
  },
  {
    "id": "stone_monolith",
    "name": "Stone Monolith",
    "group": "Monochrome & Slate",
    "darkBg": "#0C0A09",
    "darkSurface": "#1C1917",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A8A29E",
    "lightAccent": "#57534E"
  },
  {
    "id": "aluminum",
    "name": "Brushed Aluminum",
    "group": "Monochrome & Slate",
    "darkBg": "#111317",
    "darkSurface": "#1C2026",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#7DD3FC",
    "lightAccent": "#0369A1"
  },
  {
    "id": "granite",
    "name": "Granite Ridge",
    "group": "Monochrome & Slate",
    "darkBg": "#131416",
    "darkSurface": "#202226",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#9CA3AF",
    "lightAccent": "#4B5563"
  },
  {
    "id": "ironclad",
    "name": "Ironclad Forge",
    "group": "Monochrome & Slate",
    "darkBg": "#101114",
    "darkSurface": "#1B1D22",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#CBD5E1",
    "lightAccent": "#334155"
  },
  {
    "id": "tungsten",
    "name": "Tungsten Wire",
    "group": "Monochrome & Slate",
    "darkBg": "#0D0E10",
    "darkSurface": "#181A1E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FBBF24",
    "lightAccent": "#B45309"
  },
  {
    "id": "pewter",
    "name": "Antique Pewter",
    "group": "Monochrome & Slate",
    "darkBg": "#121417",
    "darkSurface": "#1E2126",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#94A3B8",
    "lightAccent": "#475569"
  },
  {
    "id": "basalt",
    "name": "Basalt Pillar",
    "group": "Monochrome & Slate",
    "darkBg": "#0B0C0E",
    "darkSurface": "#16181B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#6B7280",
    "lightAccent": "#374151"
  },
  {
    "id": "concrete",
    "name": "Polished Concrete",
    "group": "Monochrome & Slate",
    "darkBg": "#141518",
    "darkSurface": "#212328",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#64748B",
    "lightAccent": "#334155"
  },
  {
    "id": "steel_blue",
    "name": "Tempered Steel",
    "group": "Monochrome & Slate",
    "darkBg": "#0E131A",
    "darkSurface": "#18202C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "monochrome_high",
    "name": "Monochrome Contrast",
    "group": "Monochrome & Slate",
    "darkBg": "#000000",
    "darkSurface": "#161616",
    "lightBg": "#FFFFFF",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FFFFFF",
    "lightAccent": "#000000"
  },
  {
    "id": "ash_gray",
    "name": "Volcanic Ash",
    "group": "Monochrome & Slate",
    "darkBg": "#121215",
    "darkSurface": "#1E1E24",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#818CF8",
    "lightAccent": "#4F46E5"
  },
  {
    "id": "slate_ocean",
    "name": "Slate Deep Ocean",
    "group": "Monochrome & Slate",
    "darkBg": "#0A101D",
    "darkSurface": "#131E33",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#60A5FA",
    "lightAccent": "#1D4ED8"
  },
  {
    "id": "cyberpunk",
    "name": "Cyberpunk 2077",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#07070F",
    "darkSurface": "#151528",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#BE123C"
  },
  {
    "id": "neon_matrix",
    "name": "Neon Matrix",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#050D08",
    "darkSurface": "#0C1E12",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#22C55E",
    "lightAccent": "#15803D"
  },
  {
    "id": "synthwave",
    "name": "Synthwave 84",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0D031A",
    "darkSurface": "#1E0837",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D946EF",
    "lightAccent": "#A21CAF"
  },
  {
    "id": "tokyo_night",
    "name": "Tokyo Night Neon",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0B0F19",
    "darkSurface": "#161E33",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7"
  },
  {
    "id": "electric_violet",
    "name": "Electric Violet",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0A0618",
    "darkSurface": "#160F30",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#8B5CF6",
    "lightAccent": "#6D28D9"
  },
  {
    "id": "laser_cyan",
    "name": "Laser Cyan",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#041014",
    "darkSurface": "#0A2028",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#06B6D4",
    "lightAccent": "#0E7490"
  },
  {
    "id": "plasma_flare",
    "name": "Plasma Flare",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#14060B",
    "darkSurface": "#280E18",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB7185",
    "lightAccent": "#E11D48"
  },
  {
    "id": "outrun",
    "name": "Outrun Sunset",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#13081E",
    "darkSurface": "#26123C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F472B6",
    "lightAccent": "#DB2777"
  },
  {
    "id": "grid_runner",
    "name": "Grid Runner",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#060B12",
    "darkSurface": "#0E1724",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0369A1"
  },
  {
    "id": "acid_green",
    "name": "Acid Overdrive",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#081005",
    "darkSurface": "#12220D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#84CC16",
    "lightAccent": "#4D7C0F"
  },
  {
    "id": "solar_burst",
    "name": "Solar Burst",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#140E04",
    "darkSurface": "#281C0B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#B45309"
  },
  {
    "id": "vaporwave",
    "name": "Vaporwave Horizon",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#0E0B1A",
    "darkSurface": "#1C1733",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "quantum_leap",
    "name": "Quantum Leap",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#040A18",
    "darkSurface": "#0B1530",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#60A5FA",
    "lightAccent": "#1D4ED8"
  },
  {
    "id": "hologram",
    "name": "Holographic Shimmer",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#060C14",
    "darkSurface": "#0E1B2C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#2DD4BF",
    "lightAccent": "#0F766E"
  },
  {
    "id": "cyber_arcade",
    "name": "Arcade Glow",
    "group": "Cyber & Sci-Fi Neon",
    "darkBg": "#090916",
    "darkSurface": "#15152F",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A855F7",
    "lightAccent": "#7E22CE"
  },
  {
    "id": "forest_canopy",
    "name": "Emerald Forest",
    "group": "Earthy & Forest",
    "darkBg": "#020B05",
    "darkSurface": "#061D0D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#047857"
  },
  {
    "id": "moss_valley",
    "name": "Deep Moss",
    "group": "Earthy & Forest",
    "darkBg": "#061008",
    "darkSurface": "#102213",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#22C55E",
    "lightAccent": "#15803D"
  },
  {
    "id": "cedar_wood",
    "name": "Cedar Woodland",
    "group": "Earthy & Forest",
    "darkBg": "#120D0A",
    "darkSurface": "#241B15",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D97706",
    "lightAccent": "#92400E"
  },
  {
    "id": "sage_grove",
    "name": "Sage & Olive",
    "group": "Earthy & Forest",
    "darkBg": "#0B130E",
    "darkSurface": "#16241C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#84CC16",
    "lightAccent": "#4D7C0F"
  },
  {
    "id": "eucalyptus",
    "name": "Blue Eucalyptus",
    "group": "Earthy & Forest",
    "darkBg": "#071214",
    "darkSurface": "#0F2428",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#14B8A6",
    "lightAccent": "#0D9488"
  },
  {
    "id": "taiga",
    "name": "Siberian Taiga",
    "darkBg": "#061011",
    "darkSurface": "#0D2022",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#0D9488",
    "lightAccent": "#115E59",
    "group": "Earthy & Forest"
  },
  {
    "id": "clay_earth",
    "name": "Terracotta Clay",
    "group": "Earthy & Forest",
    "darkBg": "#140D0B",
    "darkSurface": "#281A16",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EA580C",
    "lightAccent": "#9A3412"
  },
  {
    "id": "bamboo",
    "name": "Bamboo Garden",
    "group": "Earthy & Forest",
    "darkBg": "#091207",
    "darkSurface": "#13240F",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#65A30D",
    "lightAccent": "#365314"
  },
  {
    "id": "evergreen",
    "name": "Pine Evergreen",
    "group": "Earthy & Forest",
    "darkBg": "#04100C",
    "darkSurface": "#0A2018",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#059669",
    "lightAccent": "#064E3B"
  },
  {
    "id": "sandstone",
    "name": "Desert Sandstone",
    "group": "Earthy & Forest",
    "darkBg": "#13100C",
    "darkSurface": "#241F18",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#CA8A04",
    "lightAccent": "#854D0E"
  },
  {
    "id": "savanna",
    "name": "Savanna Grass",
    "group": "Earthy & Forest",
    "darkBg": "#12110A",
    "darkSurface": "#242114",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EAB308",
    "lightAccent": "#A16207"
  },
  {
    "id": "rainforest",
    "name": "Tropical Rainforest",
    "group": "Earthy & Forest",
    "darkBg": "#030E09",
    "darkSurface": "#081D13",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#34D399",
    "lightAccent": "#059669"
  },
  {
    "id": "autumn_maple",
    "name": "Autumn Maple",
    "group": "Earthy & Forest",
    "darkBg": "#160B08",
    "darkSurface": "#2C1710",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F97316",
    "lightAccent": "#C2410C"
  },
  {
    "id": "peat_bog",
    "name": "Irish Peat",
    "group": "Earthy & Forest",
    "darkBg": "#11100D",
    "darkSurface": "#22201B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A16207",
    "lightAccent": "#713F12"
  },
  {
    "id": "lichen",
    "name": "Stone Lichen",
    "group": "Earthy & Forest",
    "darkBg": "#0D1210",
    "darkSurface": "#192420",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#047857"
  },
  {
    "id": "sunset_glow",
    "name": "Golden Sunset",
    "group": "Warm & Twilight",
    "darkBg": "#130B0A",
    "darkSurface": "#251715",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F97316",
    "lightAccent": "#EA580C"
  },
  {
    "id": "amber_dusk",
    "name": "Amber Dusk",
    "group": "Warm & Twilight",
    "darkBg": "#120D06",
    "darkSurface": "#241A0D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706"
  },
  {
    "id": "rose_twilight",
    "name": "Rose Twilight",
    "group": "Warm & Twilight",
    "darkBg": "#14090F",
    "darkSurface": "#27121D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#E11D48"
  },
  {
    "id": "crimson_sky",
    "name": "Crimson Sky",
    "group": "Warm & Twilight",
    "darkBg": "#140608",
    "darkSurface": "#280D11",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EF4444",
    "lightAccent": "#B91C1C"
  },
  {
    "id": "coral_reef",
    "name": "Warm Coral",
    "group": "Warm & Twilight",
    "darkBg": "#130A0E",
    "darkSurface": "#26141D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB7185",
    "lightAccent": "#E11D48"
  },
  {
    "id": "copper_patina",
    "name": "Warm Copper",
    "group": "Warm & Twilight",
    "darkBg": "#140C07",
    "darkSurface": "#28180E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EA580C",
    "lightAccent": "#C2410C"
  },
  {
    "id": "cinnamon",
    "name": "Spiced Cinnamon",
    "group": "Warm & Twilight",
    "darkBg": "#130B07",
    "darkSurface": "#26160E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D97706",
    "lightAccent": "#B45309"
  },
  {
    "id": "marigold",
    "name": "Marigold Blossom",
    "group": "Warm & Twilight",
    "darkBg": "#120E04",
    "darkSurface": "#241C09",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#EAB308",
    "lightAccent": "#CA8A04"
  },
  {
    "id": "peach_fuzz",
    "name": "Velvet Peach",
    "group": "Warm & Twilight",
    "darkBg": "#140B0B",
    "darkSurface": "#271616",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB923C",
    "lightAccent": "#EA580C"
  },
  {
    "id": "honeycomb",
    "name": "Warm Honeycomb",
    "group": "Warm & Twilight",
    "darkBg": "#120E05",
    "darkSurface": "#251C0B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706"
  },
  {
    "id": "camp_fire",
    "name": "Campfire Embers",
    "group": "Warm & Twilight",
    "darkBg": "#150805",
    "darkSurface": "#2A100B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F97316",
    "lightAccent": "#DC2626"
  },
  {
    "id": "garnet_glow",
    "name": "Garnet Gem",
    "group": "Warm & Twilight",
    "darkBg": "#15060A",
    "darkSurface": "#290D14",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#E11D48",
    "lightAccent": "#9F1239"
  },
  {
    "id": "apricot",
    "name": "Apricot Orchard",
    "group": "Warm & Twilight",
    "darkBg": "#140E0A",
    "darkSurface": "#271B14",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB923C",
    "lightAccent": "#EA580C"
  },
  {
    "id": "terra_flare",
    "name": "Terra Flare",
    "group": "Warm & Twilight",
    "darkBg": "#140C0B",
    "darkSurface": "#271916",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F87171",
    "lightAccent": "#DC2626"
  },
  {
    "id": "dusk_horizon",
    "name": "Dusk Horizon",
    "group": "Warm & Twilight",
    "darkBg": "#110C16",
    "darkSurface": "#21182A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "matrix_green",
    "name": "Matrix CRT",
    "group": "Retro & Terminal",
    "darkBg": "#020703",
    "darkSurface": "#071D0A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#00FF66",
    "lightAccent": "#059669"
  },
  {
    "id": "amber_crt",
    "name": "Amber Phosphor CRT",
    "group": "Retro & Terminal",
    "darkBg": "#0A0600",
    "darkSurface": "#1A1000",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#D97706"
  },
  {
    "id": "monochrome_green",
    "name": "VT220 Green",
    "group": "Retro & Terminal",
    "darkBg": "#000B03",
    "darkSurface": "#001D07",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#059669"
  },
  {
    "id": "commodore_64",
    "name": "Commodore 64",
    "group": "Retro & Terminal",
    "darkBg": "#090818",
    "darkSurface": "#141232",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#6366F1",
    "lightAccent": "#4338CA"
  },
  {
    "id": "apple_ii",
    "name": "Apple IIe Color",
    "group": "Retro & Terminal",
    "darkBg": "#050D06",
    "darkSurface": "#0C1B0E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#84CC16",
    "lightAccent": "#4D7C0F"
  },
  {
    "id": "solarized_dark",
    "name": "Solarized Dark",
    "group": "Retro & Terminal",
    "darkBg": "#002B36",
    "darkSurface": "#073642",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#2AA198",
    "lightAccent": "#268BD2"
  },
  {
    "id": "solarized_light",
    "name": "Solarized Light",
    "group": "Retro & Terminal",
    "darkBg": "#073642",
    "darkSurface": "#002B36",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#268BD2",
    "lightAccent": "#2AA198",
    "prefersLight": true
  },
  {
    "id": "gruvbox_dark",
    "name": "Gruvbox Dark",
    "group": "Retro & Terminal",
    "darkBg": "#282828",
    "darkSurface": "#3C3836",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FABD2F",
    "lightAccent": "#D79921"
  },
  {
    "id": "dracula",
    "name": "Dracula Classic",
    "group": "Retro & Terminal",
    "darkBg": "#282A36",
    "darkSurface": "#44475A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#BD93F9",
    "lightAccent": "#FF79C6"
  },
  {
    "id": "monokai_pro",
    "name": "Monokai Pro",
    "group": "Retro & Terminal",
    "darkBg": "#2D2A2E",
    "darkSurface": "#403E41",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FFD866",
    "lightAccent": "#FC9867"
  },
  {
    "id": "nord_polar",
    "name": "Nord Polar Night",
    "group": "Retro & Terminal",
    "darkBg": "#2E3440",
    "darkSurface": "#3B4252",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#88C0D0",
    "lightAccent": "#5E81AC"
  },
  {
    "id": "one_dark",
    "name": "Atom One Dark",
    "group": "Retro & Terminal",
    "darkBg": "#21252B",
    "darkSurface": "#282C34",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#61AFEF",
    "lightAccent": "#98C379"
  },
  {
    "id": "github_dark",
    "name": "GitHub Dark Dimmed",
    "group": "Retro & Terminal",
    "darkBg": "#1C2128",
    "darkSurface": "#2D333B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#58A6FF",
    "lightAccent": "#0969DA"
  },
  {
    "id": "palenight",
    "name": "Material Palenight",
    "group": "Retro & Terminal",
    "darkBg": "#292D3E",
    "darkSurface": "#33374C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C792EA",
    "lightAccent": "#82AAFF"
  },
  {
    "id": "synth_terminal",
    "name": "Synth Terminal",
    "group": "Retro & Terminal",
    "darkBg": "#120824",
    "darkSurface": "#221042",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FF5370",
    "lightAccent": "#F07178"
  },
  {
    "id": "parchment",
    "name": "Antique Parchment",
    "group": "Paper & Editorial",
    "darkBg": "#1A1611",
    "darkSurface": "#2A231C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D97706",
    "lightAccent": "#92400E",
    "prefersLight": true
  },
  {
    "id": "newsprint",
    "name": "Daily Newsprint",
    "group": "Paper & Editorial",
    "darkBg": "#141414",
    "darkSurface": "#222222",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#71717A",
    "lightAccent": "#3F3F46",
    "prefersLight": true
  },
  {
    "id": "manuscript",
    "name": "Scholar Manuscript",
    "group": "Paper & Editorial",
    "darkBg": "#181511",
    "darkSurface": "#28231C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#854D0E",
    "lightAccent": "#713F12",
    "prefersLight": true
  },
  {
    "id": "vellum",
    "name": "Fine Vellum",
    "group": "Paper & Editorial",
    "darkBg": "#161411",
    "darkSurface": "#25221D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A16207",
    "lightAccent": "#854D0E",
    "prefersLight": true
  },
  {
    "id": "papyrus",
    "name": "Nile Papyrus",
    "group": "Paper & Editorial",
    "darkBg": "#181510",
    "darkSurface": "#28231B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#B45309",
    "lightAccent": "#92400E",
    "prefersLight": true
  },
  {
    "id": "kraft_paper",
    "name": "Brown Kraft Paper",
    "group": "Paper & Editorial",
    "darkBg": "#191410",
    "darkSurface": "#28201A",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#B45309",
    "lightAccent": "#78350F",
    "prefersLight": true
  },
  {
    "id": "bookbinder",
    "name": "Leather Bookbinder",
    "group": "Paper & Editorial",
    "darkBg": "#18110C",
    "darkSurface": "#271C14",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C2410C",
    "lightAccent": "#9A3412"
  },
  {
    "id": "inkwell",
    "name": "Inkwell & Quill",
    "group": "Paper & Editorial",
    "darkBg": "#0B0F17",
    "darkSurface": "#151E2E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7",
    "prefersLight": true
  },
  {
    "id": "oxford_press",
    "name": "Oxford University Press",
    "group": "Paper & Editorial",
    "darkBg": "#0C101A",
    "darkSurface": "#171F32",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#002147",
    "prefersLight": true
  },
  {
    "id": "broadsheet",
    "name": "Broadsheet Journal",
    "group": "Paper & Editorial",
    "darkBg": "#141416",
    "darkSurface": "#202024",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#27272A",
    "lightAccent": "#18181B",
    "prefersLight": true
  },
  {
    "id": "letterpress",
    "name": "Letterpress Ink",
    "group": "Paper & Editorial",
    "darkBg": "#151412",
    "darkSurface": "#24221F",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#3F3F46",
    "lightAccent": "#18181B",
    "prefersLight": true
  },
  {
    "id": "archive_tan",
    "name": "Archival Box",
    "group": "Paper & Editorial",
    "darkBg": "#181613",
    "darkSurface": "#282520",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#854D0E",
    "lightAccent": "#713F12",
    "prefersLight": true
  },
  {
    "id": "calligraphy",
    "name": "Silk Calligraphy",
    "group": "Paper & Editorial",
    "darkBg": "#161413",
    "darkSurface": "#252220",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#DC2626",
    "lightAccent": "#991B1B",
    "prefersLight": true
  },
  {
    "id": "botanical_print",
    "name": "Botanical Illustration",
    "group": "Paper & Editorial",
    "darkBg": "#121614",
    "darkSurface": "#1F2622",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#166534",
    "lightAccent": "#14532D",
    "prefersLight": true
  },
  {
    "id": "ledger",
    "name": "Vintage Ledger",
    "group": "Paper & Editorial",
    "darkBg": "#131614",
    "darkSurface": "#202622",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#047857",
    "lightAccent": "#064E3B",
    "prefersLight": true
  },
  {
    "id": "lavender_mist",
    "name": "Lavender Mist",
    "group": "Pastel & Dream",
    "darkBg": "#100B1A",
    "darkSurface": "#1E1630",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A855F7",
    "lightAccent": "#7E22CE",
    "prefersLight": true
  },
  {
    "id": "mint_sorbet",
    "name": "Mint Sorbet",
    "group": "Pastel & Dream",
    "darkBg": "#071410",
    "darkSurface": "#10261F",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#34D399",
    "lightAccent": "#059669",
    "prefersLight": true
  },
  {
    "id": "blush_pink",
    "name": "Blush Blossom",
    "group": "Pastel & Dream",
    "darkBg": "#150910",
    "darkSurface": "#291220",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB7185",
    "lightAccent": "#E11D48",
    "prefersLight": true
  },
  {
    "id": "sky_pastel",
    "name": "Pastel Sky",
    "group": "Pastel & Dream",
    "darkBg": "#09111C",
    "darkSurface": "#122034",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#38BDF8",
    "lightAccent": "#0284C7",
    "prefersLight": true
  },
  {
    "id": "buttercup",
    "name": "Buttercup Yellow",
    "group": "Pastel & Dream",
    "darkBg": "#141206",
    "darkSurface": "#27230D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FACC15",
    "lightAccent": "#CA8A04",
    "prefersLight": true
  },
  {
    "id": "lilac_breeze",
    "name": "Lilac Breeze",
    "group": "Pastel & Dream",
    "darkBg": "#120D1C",
    "darkSurface": "#221A34",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA",
    "prefersLight": true
  },
  {
    "id": "melon_ice",
    "name": "Sweet Melon",
    "group": "Pastel & Dream",
    "darkBg": "#140D0B",
    "darkSurface": "#271A16",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FB923C",
    "lightAccent": "#EA580C",
    "prefersLight": true
  },
  {
    "id": "aqua_glimmer",
    "name": "Aqua Glimmer",
    "group": "Pastel & Dream",
    "darkBg": "#071317",
    "darkSurface": "#0E242C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#22D3EE",
    "lightAccent": "#0891B2",
    "prefersLight": true
  },
  {
    "id": "matcha_latte",
    "name": "Matcha Latte",
    "group": "Pastel & Dream",
    "darkBg": "#0A130B",
    "darkSurface": "#152417",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A3E635",
    "lightAccent": "#65A30D",
    "prefersLight": true
  },
  {
    "id": "fairy_tale",
    "name": "Fairy Tale Dream",
    "group": "Pastel & Dream",
    "darkBg": "#120A18",
    "darkSurface": "#241430",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F472B6",
    "lightAccent": "#DB2777",
    "prefersLight": true
  },
  {
    "id": "seafoam",
    "name": "Soft Seafoam",
    "group": "Pastel & Dream",
    "darkBg": "#081414",
    "darkSurface": "#102727",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#2DD4BF",
    "lightAccent": "#0F766E",
    "prefersLight": true
  },
  {
    "id": "periwinkle",
    "name": "Periwinkle Dream",
    "group": "Pastel & Dream",
    "darkBg": "#0D0E1C",
    "darkSurface": "#1A1C36",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#818CF8",
    "lightAccent": "#4F46E5",
    "prefersLight": true
  },
  {
    "id": "creamsicle",
    "name": "Orange Creamsicle",
    "group": "Pastel & Dream",
    "darkBg": "#140C07",
    "darkSurface": "#28180E",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FDBA74",
    "lightAccent": "#F97316",
    "prefersLight": true
  },
  {
    "id": "marshmallow",
    "name": "Marshmallow Fluff",
    "group": "Pastel & Dream",
    "darkBg": "#131118",
    "darkSurface": "#221F2B",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#E879F9",
    "lightAccent": "#C026D3",
    "prefersLight": true
  },
  {
    "id": "cloud_pink",
    "name": "Pink Sunrise Cloud",
    "group": "Pastel & Dream",
    "darkBg": "#150A11",
    "darkSurface": "#281422",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#FDA4AF",
    "lightAccent": "#E11D48",
    "prefersLight": true
  },
  {
    "id": "royal_velvet",
    "name": "Royal Velvet",
    "group": "Luxury & OLED Pure",
    "darkBg": "#07000E",
    "darkSurface": "#150028",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#A855F7",
    "lightAccent": "#7C3AED"
  },
  {
    "id": "imperial_gold",
    "name": "Imperial Gold & Black",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0C0A05",
    "darkSurface": "#1A160C",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F59E0B",
    "lightAccent": "#B45309"
  },
  {
    "id": "emerald_crown",
    "name": "Emerald Crown",
    "group": "Luxury & OLED Pure",
    "darkBg": "#04120A",
    "darkSurface": "#0A2415",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#10B981",
    "lightAccent": "#047857"
  },
  {
    "id": "ruby_sovereign",
    "name": "Sovereign Ruby",
    "group": "Luxury & OLED Pure",
    "darkBg": "#140509",
    "darkSurface": "#280B13",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#F43F5E",
    "lightAccent": "#BE123C"
  },
  {
    "id": "platinum_prestige",
    "name": "Platinum Prestige",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0E1014",
    "darkSurface": "#1A1D24",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#94A3B8",
    "lightAccent": "#334155"
  },
  {
    "id": "champagne",
    "name": "Sparkling Champagne",
    "group": "Luxury & OLED Pure",
    "darkBg": "#131109",
    "darkSurface": "#252113",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#D97706",
    "lightAccent": "#B45309"
  },
  {
    "id": "amethyst_gem",
    "name": "Deep Amethyst",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0E0616",
    "darkSurface": "#1D0E2D",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#C084FC",
    "lightAccent": "#9333EA"
  },
  {
    "id": "lapis_lazuli",
    "name": "Lapis Lazuli",
    "group": "Luxury & OLED Pure",
    "darkBg": "#060B1C",
    "darkSurface": "#0E1738",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#60A5FA",
    "lightAccent": "#2563EB"
  },
  {
    "id": "tanzanite",
    "name": "Tanzanite Royal",
    "group": "Luxury & OLED Pure",
    "darkBg": "#0A081C",
    "darkSurface": "#161238",
    "lightBg": "#FAFAFA",
    "lightSurface": "#FFFFFF",
    "darkAccent": "#818CF8",
    "lightAccent": "#4F46E5"
  }
];

export function getPresetById(id: string): ThemePresetItem {
  return THEME_PRESETS.find((p) => p.id === id) || THEME_PRESETS[0];
}
