import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {localRecord} from './browser-database';
const origin='http://localhost:3010',headers={Origin:origin},password='Transfer fixture passphrase 2026';
async function savedState(page:Page,id:string){const raw=await localRecord(page,id);return page.evaluate(async({raw,id})=>{const {key:encoded}=await(await fetch('/api/workspace?key=1')).json(),decode=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),key=await crypto.subtle.importKey('raw',decode(encoded),'AES-GCM',false,['decrypt']),envelope=JSON.parse(raw);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(envelope.iv),additionalData:new TextEncoder().encode(id)},key,decode(envelope.data))));},{raw,id});}

test('encrypted database export restores chats and generated files in a separate browser',async({browser,page})=>{
 const response=await page.request.get('/api/workspace?key=1');expect(response.ok()).toBe(true);const id=(await response.json()).id,now=Date.now();
 await page.addInitScript(data=>{localStorage.setItem('pimx_cookie_consent','rejected');localStorage.setItem('pimx_agent_v1_store',JSON.stringify(data));},{chats:[{id:'transfer-chat',title:'A portable idea',modelIds:[],toolMode:'NONE',activeTools:[],createdAt:now,updatedAt:now}],messages:{'transfer-chat':[{id:'transfer-message',chatId:'transfer-chat',role:'user',content:'private-transfer-marker',state:'DONE',createdAt:now}]},webFiles:{'transfer-chat':[{path:'index.html',content:'<h1>private-generated-marker</h1>'}]},settings:{aiReactions:false}});
 await page.goto('/chat');await expect(page.locator('#composer-input')).toBeVisible();await expect.poll(()=>localRecord(page,id)).toBeTruthy();
 await page.goto('/data');await page.locator('.database-transfer input[name="passphrase"]').fill(password);await page.locator('input[name="confirmPassphrase"]').fill(password);
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Export chat database',exact:true}).click();const download=await downloaded,path=(await download.path())!,raw=readFileSync(path,'utf8');expect(JSON.parse(raw).format).toBe('PIMX-CHAT-DATABASE');expect(raw).not.toContain('private-transfer-marker');expect(raw).not.toContain('private-generated-marker');
 const target=await browser.newContext();
 try{const other=await target.newPage();await other.goto('/data');await expect(other.getByRole('button',{name:'Upload chat database',exact:true})).toBeEnabled();
 await other.locator('.database-transfer input[name="passphrase"]').fill('An incorrect transfer passphrase');await other.locator('input[name="database"]').setInputFiles(path);await other.getByRole('button',{name:'Upload chat database',exact:true}).click();await expect(other.locator('.database-transfer [role="alert"]')).toContainText('incorrect');
 await other.locator('.database-transfer input[name="passphrase"]').fill(password);await other.getByRole('button',{name:'Upload chat database',exact:true}).click();await other.getByRole('button',{name:'Import database',exact:true}).click();await expect(other.locator('#composer-input')).toBeVisible();
 const otherId=(await (await other.request.get('/api/workspace')).json()).id;expect(otherId).not.toBe(id);const state=await savedState(other,otherId);expect(state.messages['transfer-chat'][0].content).toBe('private-transfer-marker');expect(state.webFiles['transfer-chat'][0].content).toContain('private-generated-marker');expect(JSON.parse(await localRecord(other,otherId)).v).toBe(2);expect((await(await other.request.get('/api/workspace')).json()).state).toBeNull();
 }finally{await target.close();}
});
test('removed auth routes lead straight to an open workspace',async({page,request})=>{
 for(const path of ['/login','/signup','/forgot-password','/reset-password','/admin']){await page.goto(path);await expect(page.locator('#composer-input')).toBeVisible();await expect(page).toHaveURL(/\/chat$/);expect(await page.locator('input[name="email"],input[name="username"],input[name="password"]').count()).toBe(0);}
 for(const path of ['/api/auth/login','/api/auth/signup','/api/auth/reset-password','/api/account','/api/admin'])expect((await request.post(path,{headers,data:{}})).status()).toBe(404);
});
test('English default, Persian navigation, theme photographs and product film work',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('pimx_cookie_consent','rejected'));await page.goto('/');await expect(page.locator('html')).toHaveAttribute('lang','en');await expect(page.locator('.product-stage img')).toHaveAttribute('src','/media/pimx-workspace-dark.webp');
 await page.getByRole('button',{name:'Toggle theme'}).click();await expect(page.locator('.product-stage img')).toHaveAttribute('src','/media/pimx-workspace-light.webp');
 await page.getByRole('button',{name:'فارسی',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.locator('h1')).toContainText('واقعی');await expect(page.getByRole('link',{name:'ادامه بدون لاگین',exact:true})).toHaveAttribute('href','https://chat.pimxagent.pages.dev/fa/');expect(await page.locator('a[href*="signup"],a[href*="login"]').count()).toBe(0);
 await page.goto('/');await page.getByRole('button',{name:'پخش ویدیو',exact:true}).click();await expect.poll(()=>page.locator('video').evaluate((video:HTMLVideoElement)=>video.currentTime)).toBeGreaterThan(0);expect(await page.locator('video').evaluate((video:HTMLVideoElement)=>video.duration)).toBeGreaterThan(14);
});
test('the installed shell shows Persian offline guidance for a Persian route',async({page,context})=>{
 await page.addInitScript(()=>localStorage.setItem('pimx_cookie_consent','rejected'));await page.goto('/fa/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await expect.poll(()=>page.evaluate(()=>!!navigator.serviceWorker.controller)).toBe(true);
 // Reproduce Pages' clean-URL redirect metadata in the cached HTML response.
 const redirected=await page.evaluate(async()=>{const response=await fetch('/offline.html/'),result={ok:response.ok,redirected:response.redirected};const key=(await caches.keys()).find(key=>key.startsWith('pimx-shell-'))!;await(await caches.open(key)).put('/offline.html',response);return result;});expect(redirected).toEqual({ok:true,redirected:true});
 await context.setOffline(true);await page.goto('/fa/offline-probe',{waitUntil:'domcontentloaded'});await expect(page.locator('html')).toHaveAttribute('lang','fa');await expect(page.locator('h1')).toHaveText('لحظه‌ای بدون اینترنت.');await expect(page.getByRole('link',{name:'تلاش دوباره'})).toHaveAttribute('href','/fa/');
});

for(const locale of ['en','fa'])test('capability ticker stays visible and seamless over three cycles in '+locale,async({page})=>{for(const width of [1440,300]){await page.setViewportSize({width,height:900});await page.goto(locale==='fa'?'/fa/':'/');await expect.poll(()=>page.locator('.marquee-track').evaluate(element=>{void getComputedStyle(element).transform;return element.getAnimations().length;})).toBe(1);const result=await page.locator('.marquee-track').evaluate(track=>{const groups=Array.from(track.children) as HTMLElement[],animation=track.getAnimations()[0],duration=Number(animation.effect!.getTiming().duration),container=track.parentElement!.getBoundingClientRect();animation.pause();const frames=[];for(const time of [0,duration-1,duration+1,2*duration-1,2*duration+1,3*duration+1]){animation.currentTime=time;const a=groups[0].getBoundingClientRect(),b=groups[1].getBoundingClientRect();frames.push({gap:Math.abs(a.right-b.left),left:Math.min(a.left,b.left)-container.left,right:Math.max(a.right,b.right)-container.right});}return {duration,iterations:animation.effect!.getTiming().iterations,equal:groups[0].innerHTML===groups[1].innerHTML,widths:groups.map(g=>g.getBoundingClientRect().width),direction:getComputedStyle(track.parentElement!).direction,frames};});expect(result.direction).toBe('ltr');expect(result.duration).toBeGreaterThan(0);expect(result.iterations).toBe(Infinity);expect(result.equal).toBe(true);expect(result.widths[0]).toBeCloseTo(result.widths[1],2);for(const frame of result.frames){expect(frame.gap).toBeLessThan(1);expect(frame.left).toBeLessThanOrEqual(1);expect(frame.right).toBeGreaterThanOrEqual(-1);}}});
