'use client';
import { decryptSecret } from '@/lib/crypto';

let key: CryptoKey | null=null,owner='',state:Record<string,unknown>={},queue=Promise.resolve();
export const vaultStorageKey=(id:string)=>`pimx_agent_v2:${id}`;
const encode=(bytes:Uint8Array)=>{let text='';for(let i=0;i<bytes.length;i+=32768)text+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(text);};
const decode=(value:string)=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
let pendingUnlock: { id:string; promise:Promise<Record<string,unknown>> } | undefined;
export function unlockVault(id:string,providedKey?:string){if(pendingUnlock?.id===id)return pendingUnlock.promise;const promise=performUnlock(id,providedKey);pendingUnlock={id,promise};promise.catch(()=>{if(pendingUnlock?.promise===promise)pendingUnlock=undefined;});return promise;}
async function performUnlock(id:string,providedKey?:string) {
  let encodedKey=providedKey;if(!encodedKey){const response=await fetch('/api/workspace?key=1',{cache:'no-store'});if(!response.ok)throw new Error('Your workspace could not be opened.');const data=await response.json();if(data.id!==id)throw new Error('Workspace identity changed. Reload the page.');encodedKey=data.key;}
  key=await crypto.subtle.importKey('raw',decode(encodedKey!),'AES-GCM',false,['encrypt','decrypt']);owner=id;
  const record=await databaseOperation('readonly',store=>store.get(id));
  const saved=typeof record==='string'?record:localStorage.getItem(vaultStorageKey(id)),legacy=localStorage.getItem('pimx_agent_v1_store');
  if(saved){const envelope=JSON.parse(saved);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(envelope.iv),additionalData:new TextEncoder().encode(id)},key,decode(envelope.data));state=JSON.parse(new TextDecoder().decode(plain));}
  else if(legacy){state=JSON.parse(legacy);await writeLocal(state);localStorage.removeItem('pimx_agent_v1_store');}
  else state={};
  const accounts=Array.isArray(state.accounts)?state.accounts as Record<string,unknown>[]:[];
  for(const account of accounts){if(typeof account.apiKey==='string' && account.apiKey && !account.credentialId){const migrated=await fetch('/api/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:account.providerId,label:account.label || 'Imported key',apiKey:decryptSecret(account.apiKey),baseUrl:account.baseUrlOverride || (state.customProviders as Record<string,unknown>[] | undefined)?.find(provider=>provider.id===account.providerId)?.baseUrl,apiFormat:(state.customProviders as Record<string,unknown>[] | undefined)?.find(provider=>provider.id===account.providerId)?.apiFormat})});if(!migrated.ok)throw new Error('An older provider key could not be moved to the secure vault. Retry or reconnect that provider.');const {credential}=await migrated.json();account.credentialId=credential.id;account.keyPreview=credential.keyPreview;account.apiKey='';delete account.sessionToken;delete account.extraHeadersJson;}}
  const stored=await fetch('/api/credentials',{cache:'no-store'});if(!stored.ok)throw new Error('Your provider vault could not be loaded.');
  const {credentials}=await stored.json();
  state.accounts=credentials.map((credential:Record<string,unknown>,i:number)=>{const existing=accounts.find(account=>account.credentialId===credential.id);return {id:credential.id,providerId:credential.providerId,label:credential.label,credentialId:credential.id,keyPreview:credential.keyPreview,baseUrlOverride:credential.baseUrl,priority:i,enabled:true,status:'CONNECTED',requestCount:0,failureCount:0,...existing,apiKey:'',sessionToken:undefined,extraHeadersJson:undefined,apiFormat:credential.apiFormat};});
  await writeLocal(state);localStorage.removeItem(vaultStorageKey(id));return state;
}
async function databaseOperation(mode:IDBTransactionMode,operation:(store:IDBObjectStore)=>IDBRequest):Promise<unknown>{return new Promise((resolve,reject)=>{const opening=indexedDB.open('pimx-private-workspace',1);opening.onupgradeneeded=()=>opening.result.createObjectStore('workspaces');opening.onerror=()=>reject(opening.error);opening.onsuccess=()=>{const db=opening.result,transaction=db.transaction('workspaces',mode),request=operation(transaction.objectStore('workspaces'));transaction.oncomplete=()=>{resolve(request.result);db.close();};transaction.onerror=()=>{reject(transaction.error);db.close();};transaction.onabort=()=>{reject(transaction.error);db.close();};};});}
async function writeLocal(value:Record<string,unknown>) {if(!key || !owner)return;const id=owner,activeKey=key,iv=crypto.getRandomValues(new Uint8Array(12)),data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},activeKey,new TextEncoder().encode(JSON.stringify(value)));if(owner===id)await databaseOperation('readwrite',store=>store.put(JSON.stringify({v:2,iv:encode(iv),data:encode(new Uint8Array(data))}),id));}
export function loadVaultState(){return state;}
export function saveVaultState(value:Record<string,unknown>){if(!key)return;state=value;const id=owner;window.dispatchEvent(new CustomEvent('pimx-vault-status',{detail:'saving'}));queue=queue.then(async()=>{if(owner!==id)return;await writeLocal(value);window.dispatchEvent(new CustomEvent('pimx-vault-status',{detail:'saved'}));}).catch(()=>{window.dispatchEvent(new CustomEvent('pimx-vault-status',{detail:'error'}));});}
export async function deleteLocalVault(id:string){await queue;await databaseOperation('readwrite',store=>store.delete(id));localStorage.removeItem(vaultStorageKey(id));}
export function lockVault(){pendingUnlock=undefined;key=null;owner='';state={};}
const MAX_BACKUP=100*1024*1024;
async function transferKey(passphrase:string,salt:Uint8Array){if(passphrase.length<12 || passphrase.length>256)throw new Error('Use a transfer passphrase of 12 to 256 characters.');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(passphrase),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:new Uint8Array(salt),iterations:600000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
function cleanTransfer(value:Record<string,unknown>){return JSON.parse(JSON.stringify(value, (name,item)=>['__proto__','constructor','prototype','apiKey','sessionToken','extraHeadersJson'].includes(name)?undefined:item)) as Record<string,unknown>;}
export async function exportChatDatabase(passphrase:string){if(!key)throw new Error('Open your workspace before transferring its database.');await queue;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode(JSON.stringify(cleanTransfer({chats:[],messages:{},...state})));if(plain.length>MAX_BACKUP)throw new Error('The database exceeds the 100 MB transfer limit.');const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('PIMX-CHAT-DATABASE:1')},await transferKey(passphrase,salt),plain);return new Blob([JSON.stringify({format:'PIMX-CHAT-DATABASE',version:1,createdAt:new Date().toISOString(),kdf:'PBKDF2-SHA256',iterations:600000,salt:encode(salt),iv:encode(iv),data:encode(new Uint8Array(encrypted))})],{type:'application/json'});}
export async function readChatDatabase(file:File,passphrase:string){if(file.size>MAX_BACKUP*1.4)throw new Error('The database file is too large.');let data:Record<string,unknown>;try{const envelope=JSON.parse(await file.text());if(envelope.format!=='PIMX-CHAT-DATABASE'||envelope.version!==1||envelope.kdf!=='PBKDF2-SHA256'||envelope.iterations!==600000||typeof envelope.data!=='string')throw new Error();const salt=decode(envelope.salt),iv=decode(envelope.iv);if(salt.length!==16||iv.length!==12)throw new Error();const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('PIMX-CHAT-DATABASE:1')},await transferKey(passphrase,salt),decode(envelope.data));if(plain.byteLength>MAX_BACKUP)throw new Error();data=cleanTransfer(JSON.parse(new TextDecoder().decode(plain)));}catch{throw new Error('The passphrase is incorrect or the database file is invalid.');}
  if(!data || typeof data!=='object' || Array.isArray(data) || !Array.isArray(data.chats) || !data.messages || typeof data.messages!=='object')throw new Error('This is not a compatible chat database.');
  for(const field of ['chats','accounts','projects','models','artifacts','sources','sourceChunks','memories','personas','knowledgeBases','customProviders','customFonts','logs'])if(data[field]!==undefined && !Array.isArray(data[field]))throw new Error('This is not a compatible chat database.');
  for(const field of ['messages','settings','canvasDocuments','webProjects','webFiles','slideDecks','learningSessions'])if(data[field]!==undefined && (!data[field]||typeof data[field]!=='object'||Array.isArray(data[field])))throw new Error('This is not a compatible chat database.');
  if(data.chats.some((chat:Record<string,unknown>)=>!chat||typeof chat.id!=='string'||chat.temporary===true))throw new Error('This is not a compatible chat database.');return data;
}
export async function importChatDatabase(data:Record<string,unknown>){if(!key)throw new Error('Open your workspace before transferring its database.');await queue;const next={...data,accounts:state.accounts};await writeLocal(next);state=next;pendingUnlock=undefined;}
