'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Turnstile} from './Turnstile';
import {useLocale} from '@/components/i18n/LocaleProvider';
import {localizedHref} from '@/lib/i18n/text';
import {translate} from '@/lib/i18n/text';
export function AuthForm({mode,next='/'}:{mode:'login'|'signup'|'forgot-password'|'reset-password';next?:string}){const locale=useLocale(),fa=locale==='fa',c=(en:string,faText:string)=>fa?faText:en,h=(path:string)=>localizedHref(path,locale);const [pending,setPending]=useState(false),[error,setError]=useState(''),[token,setToken]=useState(''),[attempt,setAttempt]=useState(0),[success,setSuccess]=useState('');const signup=mode==='signup',forgot=mode==='forgot-password',reset=mode==='reset-password',recovery=forgot||reset;
return <div className="auth-layout"><div className="auth-story"><span className="site-eyebrow">{c('PIMX / YOUR WORKSPACE','PIMX / فضای کاری شما')}</span><h1>{signup?c('A place for your next great idea.','جایی برای ایدهٔ بعدی شما.'):recovery?c('A fresh start.','یک شروع تازه.'):c('Welcome back to your creative orbit.','به مدار خلاقیت‌تان برگردید.')}</h1><p>{c('Your conversations, projects and models — behind a secure sign-in.','گفتگوها، پروژه‌ها و مدل‌های شما؛ پشت یک ورود امن.')}</p><div className="auth-seal"><span>◇</span><div><b>{c('Protected from the first step','امنیت از اولین قدم')}</b><p>{c('Secure sessions. Encrypted keys. Chats on your device.','نشست امن. کلید رمزگذاری‌شده. چت روی دستگاه شما.')}</p></div></div></div><form className="site-form" onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);if((signup||reset)&&form.get('password')!==form.get('confirmPassword')){setError(c('The passwords do not match.','گذرواژه‌ها یکسان نیستند.'));return;}setPending(true);setError('');setSuccess('');try{const payload=reset?{token:new URLSearchParams(location.search).get('token'),password:form.get('password'),confirmPassword:form.get('confirmPassword')}:forgot?{email:form.get('email'),website:form.get('website'),turnstileToken:token||undefined,locale}:{email:form.get('email'),password:form.get('password'),...(signup?{username:form.get('username'),birthYear:Number(form.get('birthYear')),confirmPassword:form.get('confirmPassword')}:{}),website:form.get('website'),turnstileToken:token||undefined,locale};const response=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error?.message||'The request could not be completed.');if(forgot){setSuccess(c('If this email belongs to an account, a reset link has been sent. Check your inbox and spam folder.','اگر این ایمیل متعلق به حسابی باشد، لینک بازیابی ارسال شده است. صندوق ورودی و پوشهٔ اسپم را بررسی کنید.'));setPending(false);}else if(reset){setSuccess(c('Your password has been reset. Sign in with your new password.','گذرواژه بازنشانی شد. با گذرواژهٔ جدید وارد شوید.'));setPending(false);}else window.location.assign(signup?h('/thank-you')+'?created=1&email='+(result.emailSent?'sent':'pending'):next);}catch(error){setToken('');setAttempt(value=>value+1);setError(fa?authError(error instanceof Error?error.message:'Network error.'):error instanceof Error?error.message:'Network error.');setPending(false);}}}>
<span className="site-eyebrow">{signup?c('CREATE AN ACCOUNT','ساخت حساب'):recovery?c('ACCOUNT RECOVERY','بازیابی حساب'):c('SECURE SIGN-IN','ورود امن')}</span><h2>{signup?c('Create your workspace','فضای کاری‌تان را بسازید'):forgot?c('Forgot your password?','گذرواژه را فراموش کرده‌اید؟'):reset?c('Choose a new password','گذرواژهٔ جدید انتخاب کنید'):c('Good to see you again','خوش آمدید')}</h2>
{signup&&<><label>{c('Username','نام کاربری')}<input name="username" autoComplete="username" minLength={3} maxLength={32} pattern="[\p{L}\p{N}_]+" required/><small>{c('3–32 letters, numbers or underscores.','۳ تا ۳۲ حرف، عدد یا زیرخط.')}</small></label><label>{c('Birth year (Gregorian)','سال تولد (میلادی)')}<input name="birthYear" type="number" inputMode="numeric" min={1900} max={new Date().getFullYear()} autoComplete="bday-year" required dir="ltr"/></label></>}
{!reset&&<label>{c('Email address','ایمیل حساب')}<input name="email" type="email" dir="ltr" autoComplete="email" maxLength={254} required/></label>}{!forgot&&<label>{reset?c('New password','گذرواژهٔ جدید'):c('Password','گذرواژه')}<input name="password" type="password" dir="ltr" autoComplete={signup||reset?'new-password':'current-password'} minLength={12} maxLength={128} required/></label>}{(signup||reset)&&<><label>{c('Repeat password','تکرار گذرواژه')}<input name="confirmPassword" type="password" dir="ltr" autoComplete="new-password" minLength={12} maxLength={128} required/></label><small>{c('At least 12 characters. Use a long, unique passphrase.','حداقل ۱۲ نویسه؛ از عبارت طولانی و منحصربه‌فرد استفاده کنید.')}</small></>}
{!recovery&&!signup&&<Link className="text-link" href={h('/forgot-password')}>{c('Forgot password?','گذرواژه را فراموش کرده‌اید؟')}</Link>}{!reset&&<><label className="form-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><Turnstile key={attempt} action={mode} onToken={setToken}/></>}
{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}<button className="site-button" disabled={pending}>{pending?c('Connecting securely…','در حال اتصال امن…'):signup?c('Create account','ساخت حساب'):forgot?c('Send reset email','ارسال ایمیل بازیابی'):reset?c('Reset password','بازنشانی گذرواژه'):c('Open my workspace','ورود به فضای کاری')}</button>{recovery?<Link href={h('/login')}>{c('Back to sign in','بازگشت به ورود')}</Link>:<><p className="form-footnote">{c('By continuing, you accept our ','با ادامه، ')}<Link href={h('/terms')}>{c('Terms','شرایط استفاده')}</Link>{c(' and ',' و ')}<Link href={h('/privacy')}>{c('Privacy Policy','سیاست حریم خصوصی')}</Link>{fa?' را می‌پذیرید.':'.'}</p><p className="form-switch">{signup?c('Already have an account?','قبلاً حساب ساخته‌اید؟'):c('New here?','حساب ندارید؟')} <Link href={h(signup?'/login':'/signup')}>{signup?c('Sign in','وارد شوید'):c('Create an account','ثبت‌نام کنید')}</Link></p></>}
</form></div>;
}
export function authError(message:string){if(/^Check .+\.$/.test(message))return translate('Check {0}.','fa',message.slice(6,-1).split(', ').map(field=>translate(field,'fa')).join('، '));const errors:Record<string,string>={'The email or password is incorrect.':'ایمیل یا گذرواژه نادرست است.','An account with this email or username already exists.':'این ایمیل یا نام کاربری قبلاً ثبت شده است.','The passwords do not match.':'گذرواژه‌ها یکسان نیستند.','Email delivery is not configured yet. Please contact support.':'ارسال ایمیل هنوز تنظیم نشده است. با پشتیبانی تماس بگیرید.','The email could not be delivered. Please try again shortly.':'ارسال ایمیل انجام نشد. کمی بعد دوباره تلاش کنید.','This reset link is invalid or expired. Request a new one.':'لینک بازیابی معتبر نیست یا منقضی شده است. لینک جدید درخواست کنید.','Network error.':'اتصال برقرار نشد. دوباره تلاش کنید.','Too many requests. Please try again later.':'درخواست‌ها بیش از حد مجاز است. کمی بعد دوباره تلاش کنید.','Complete the security challenge.':'تأیید امنیتی را انجام دهید.'};return errors[message]||translate(message,'fa');}
