import Link from 'next/link';
import {SiteFrame} from './SiteFrame';
import {getLocale} from '@/lib/i18n/server';
import {localizedHref} from '@/lib/i18n/text';
const privacy=[
 [['No signup or personal profile',"بدون ثبت‌نام و پروفایل شخصی"],['We do not ask for an email, password, username or birth year. An automatic HttpOnly cookie identifies this browser’s private workspace. Its random token is stored only as a hash; the encryption key is encrypted on the server. Different browsers have separate workspaces.',"ایمیل، رمز عبور، نام کاربری یا سال تولد درخواست نمی‌کنیم. کوکی خودکار HttpOnly فضای کاری خصوصی این مرورگر را مشخص می‌کند. توکن تصادفی فقط به صورت هش و کلید رمزگذاری به صورت رمزگذاری‌شده در سرور نگهداری می‌شود. هر مرورگر فضای کاری جداگانه دارد."]],
 [['Private chats stay on your device','چت خصوصی روی دستگاه شما می‌ماند'],['Saved conversations, projects, files and generated artifacts are encrypted in your browser’s IndexedDB. They are not automatically backed up to our server. Clearing browser storage can erase them. Use encrypted database export before changing devices or clearing data. You choose the transfer passphrase; we cannot recover it.','گفتگو، پروژه، فایل و خروجی ذخیره‌شده در IndexedDB مرورگر رمزگذاری می‌شود و خودکار روی سرور پشتیبان‌گیری نمی‌شود. پاک کردن حافظهٔ مرورگر می‌تواند آن‌ها را حذف کند. پیش از تغییر دستگاه یا پاک کردن داده، خروجی رمزگذاری‌شده بگیرید. گذرواژهٔ انتقال را شما انتخاب می‌کنید و ما امکان بازیابی آن را نداریم.']],
 [['Models and API keys','مدل‌ها و کلید API'],['Provider keys are encrypted in the server vault and are never returned to the browser after saving. The messages and files required to answer your request pass through our API to your chosen model provider. That provider processes them under its own policy.','کلید ارائه‌دهنده در مخزن سرور رمزگذاری می‌شود و پس از ذخیره دوباره به مرورگر برگردانده نمی‌شود. پیام و فایل لازم برای پاسخ از API ما به ارائه‌دهندهٔ مدل منتخب شما ارسال می‌شود. پردازش ارائه‌دهنده تابع سیاست خودش است.']],
 [['Temporary chats and public sharing','گفتگوی موقت و اشتراک عمومی'],['Temporary chat content stays in memory and is excluded from saved history and exports. Requests still reach your selected model. Publishing a share link explicitly saves an encrypted snapshot on the server, accessible to anyone with the link for seven days or until you revoke it. API keys, system prompts and attachments are excluded.','محتوای چت موقت فقط در حافظه می‌ماند و در تاریخچه و خروجی ذخیره نمی‌شود. درخواست همچنان به مدل منتخب ارسال می‌شود. ایجاد لینک اشتراک، با انتخاب شما یک نسخهٔ رمزگذاری‌شده روی سرور می‌سازد که دارندگان لینک تا هفت روز یا زمان لغو به آن دسترسی دارند. کلید API، دستور سیستمی و پیوست در نسخهٔ عمومی نیست.']],
 [['Optional visit analytics',"آمار اختیاری بازدید"],['Analytics runs only after you accept it. We record the visited page, browser, device category and approximate country/city supplied by Cloudflare. A random browser identifier is hashed before storage. No personal account, GPS or chat text is included.',"آمار فقط پس از پذیرش شما فعال می‌شود. صفحهٔ بازدیدشده، مرورگر، دستهٔ دستگاه و کشور یا شهر تقریبی ارائه‌شده توسط Cloudflare ثبت می‌شود. شناسهٔ تصادفی مرورگر پیش از ذخیره هش می‌شود. حساب شخصی، GPS یا متن چت در آن قرار ندارد."]],
 [['Contact and support',"تماس و پشتیبانی"],['Contact form messages are encrypted in our internal inbox. Cloudflare Turnstile processes the information needed for its anti-bot challenge. Do not include provider keys or private chat content in support requests. You can also contact pimxagent@gmail.com directly.',"پیام فرم تماس در صندوق داخلی رمزگذاری می‌شود. Cloudflare Turnstile اطلاعات لازم برای چالش ضدربات را پردازش می‌کند. کلید ارائه‌دهنده یا محتوای خصوصی چت را در پیام پشتیبانی قرار ندهید. می‌توانید مستقیم به pimxagent@gmail.com ایمیل بفرستید."]],
 [['Your controls',"کنترل داده‌ها"],['Delete chats and projects on your device, revoke share links and remove provider credentials at any time. Export before clearing cookies or browser storage: removing the workspace cookie can make saved ciphertext inaccessible. Exports and copies on other devices remain under your control. Analytics expires after 90 days and can be disabled in Cookie settings.',"هر زمان می‌توانید چت و پروژه را از دستگاه حذف کنید، لینک اشتراک را لغو کنید و کلید ارائه‌دهنده را بردارید. قبل از پاک کردن کوکی یا دادهٔ مرورگر خروجی بگیرید؛ حذف کوکی فضای کاری می‌تواند دادهٔ رمزگذاری‌شده را غیرقابل دسترس کند. فایل خروجی و نسخهٔ دستگاه‌های دیگر در اختیار شماست. آمار پس از ۹۰ روز پاک می‌شود و از تنظیمات کوکی قابل غیرفعال کردن است."]],
];
const terms=[
 [['Open access and connected models',"دسترسی مستقیم و مدل‌های متصل"],['No account or membership is required to use the workspace and its tools. Keep your provider keys private. Connecting a key authorizes its use for requests from this browser’s workspace. Provider charges, model access and usage limits follow that provider?s terms.',"فضای کاری و ابزارها به حساب یا عضویت نیاز ندارند. کلید ارائه‌دهنده را خصوصی نگه دارید. با اتصال کلید، استفاده از آن برای درخواست‌های فضای کاری این مرورگر را مجاز می‌کنید. هزینه، دسترسی مدل و سقف مصرف تابع شرایط آن ارائه‌دهنده است."]],
 [['Content and results','محتوا و نتیجه'],['Upload only material you have the right to use. AI responses may be incomplete or wrong. Review important decisions, generated code and professional information before acting or publishing. Images and sources retain their original licenses.','فقط محتوایی را بارگذاری کنید که حق استفاده از آن را دارید. پاسخ هوش مصنوعی می‌تواند ناقص یا اشتباه باشد. تصمیم مهم، کد تولیدشده و اطلاعات تخصصی را پیش از استفاده یا انتشار بررسی کنید. عکس و منبع تابع مجوز اصلی خود است.']],
 [['Acceptable use','استفادهٔ مجاز'],['Do not bypass access controls, access another user’s records, extract secrets, distribute malware or abuse APIs. Excessive or suspicious requests may be limited or blocked.','دور زدن کنترل دسترسی، خواندن رکورد دیگران، استخراج اسرار، انتشار بدافزار و سوءاستفاده از API مجاز نیست. درخواست بیش از حد یا مشکوک ممکن است محدود یا مسدود شود.']],
 [['Availability and your database','دسترسی و دیتابیس شما'],['Models and web search depend on third-party services and internet access. Private chats are stored on your device; you are responsible for exporting important data before clearing browser storage. Continuous, error-free availability is not guaranteed.','مدل و جست‌وجوی وب به سرویس‌های بیرونی و اینترنت وابسته است. چت خصوصی روی دستگاه شماست؛ پیش از پاک کردن حافظهٔ مرورگر از اطلاعات مهم خروجی بگیرید. دسترسی دائمی و بی‌خطا تضمین نمی‌شود.']],
 [['Changes and support','تغییرات و پشتیبانی'],['Features and these terms may be updated. The date on this page identifies the latest revision. For questions, contact pimxagent@gmail.com or use our contact form.','امکانات و شرایط ممکن است به‌روزرسانی شوند. تاریخ این صفحه آخرین تغییر را مشخص می‌کند. برای پرسش با pimxagent@gmail.com یا فرم تماس ارتباط بگیرید.']],
];
export async function LegalPage({kind}:{kind:'privacy'|'terms'}){const locale=await getLocale(),i=locale==='fa'?1:0,rows=kind==='privacy'?privacy:terms;return <SiteFrame><article className="prose-page"><span className="site-eyebrow">{i?'به‌روزرسانی: ۲۷ سپتامبر ۲۰۲۶':'UPDATED SEPTEMBER 28, 2026'}</span><h1>{kind==='privacy'?(i?'اطلاعات شما چگونه استفاده می‌شود؟':'Your data, explained.'):(i?'شرایط استفاده از PIMX Agent':'Terms of use')}</h1><p>{i?'با استفاده از سایت، شرایط و روش حفظ حریم خصوصی را بپذیرید و دادهٔ مهم را روی دستگاه خودتان حفظ کنید.':'Understand how your workspace works and keep a copy of the data that matters to you.'}</p>{rows.map((row,index)=><section key={index}><h2>{row[0][i]}</h2><p>{row[1][i]}</p></section>)}<p><Link href={localizedHref('/data',locale)}>{i?'حساب و انتقال دیتابیس':'Save & transfer chats'}</Link> · <Link href={localizedHref('/contact',locale)}>{i?'تماس با ما':'Contact us'}</Link> · <a href="mailto:pimxagent@gmail.com">pimxagent@gmail.com</a></p></article></SiteFrame>;}
