import Link from 'next/link';
import {SiteFrame} from './SiteFrame';
import {getLocale} from '@/lib/i18n/server';
import {localizedHref} from '@/lib/i18n/text';
const privacy=[
 [['Account and sign-in','حساب و ورود'],['We store your username, birth year and encrypted email in Cloudflare D1. Passwords are hashed with a server-only pepper. Session cookies are HttpOnly, secure over HTTPS and inaccessible to page scripts.','نام کاربری، سال تولد و ایمیل رمزگذاری‌شده در Cloudflare D1 ذخیره می‌شود. گذرواژه با کلید خصوصی سرور هش می‌شود. کوکی نشست HttpOnly و در HTTPS امن است و اسکریپت صفحه به آن دسترسی ندارد.']],
 [['Private chats stay on your device','چت خصوصی روی دستگاه شما می‌ماند'],['Saved conversations, projects, files and generated artifacts are encrypted in your browser’s IndexedDB. They are not automatically backed up to our server. Clearing browser storage can erase them. Use encrypted database export before changing devices or clearing data. You choose the transfer passphrase; we cannot recover it.','گفتگو، پروژه، فایل و خروجی ذخیره‌شده در IndexedDB مرورگر رمزگذاری می‌شود و خودکار روی سرور پشتیبان‌گیری نمی‌شود. پاک کردن حافظهٔ مرورگر می‌تواند آن‌ها را حذف کند. پیش از تغییر دستگاه یا پاک کردن داده، خروجی رمزگذاری‌شده بگیرید. گذرواژهٔ انتقال را شما انتخاب می‌کنید و ما امکان بازیابی آن را نداریم.']],
 [['Models and API keys','مدل‌ها و کلید API'],['Provider keys are encrypted in the server vault and are never returned to the browser after saving. The messages and files required to answer your request pass through our API to your chosen model provider. That provider processes them under its own policy.','کلید ارائه‌دهنده در مخزن سرور رمزگذاری می‌شود و پس از ذخیره دوباره به مرورگر برگردانده نمی‌شود. پیام و فایل لازم برای پاسخ از API ما به ارائه‌دهندهٔ مدل منتخب شما ارسال می‌شود. پردازش ارائه‌دهنده تابع سیاست خودش است.']],
 [['Temporary chats and public sharing','گفتگوی موقت و اشتراک عمومی'],['Temporary chat content stays in memory and is excluded from saved history and exports. Requests still reach your selected model. Publishing a share link explicitly saves an encrypted snapshot on the server, accessible to anyone with the link for seven days or until you revoke it. API keys, system prompts and attachments are excluded.','محتوای چت موقت فقط در حافظه می‌ماند و در تاریخچه و خروجی ذخیره نمی‌شود. درخواست همچنان به مدل منتخب ارسال می‌شود. ایجاد لینک اشتراک، با انتخاب شما یک نسخهٔ رمزگذاری‌شده روی سرور می‌سازد که دارندگان لینک تا هفت روز یا زمان لغو به آن دسترسی دارند. کلید API، دستور سیستمی و پیوست در نسخهٔ عمومی نیست.']],
 [['Visits, devices and approximate location','بازدید، دستگاه و موقعیت تقریبی'],['Optional analytics is enabled only after you accept it. It stores page visits, browser, device category and an approximate country/city supplied by Cloudflare. A random browser identifier is hashed before storage; an account ID can be associated with a signed-in visit. We do not request GPS or store chat text in analytics. Security sign-in events record device and approximate location separately to protect accounts.','آمار اختیاری فقط پس از پذیرش فعال می‌شود و بازدید صفحه، مرورگر، دستهٔ دستگاه و کشور یا شهر تقریبی ارائه‌شده توسط Cloudflare را ثبت می‌کند. شناسهٔ تصادفی مرورگر پیش از ذخیره هش می‌شود و بازدید کاربر واردشده می‌تواند به شناسهٔ حساب مرتبط شود. GPS درخواست نمی‌شود و متن چت در آمار قرار نمی‌گیرد. رویدادهای امنیتی ورود برای محافظت از حساب، دستگاه و موقعیت تقریبی را جداگانه ثبت می‌کنند.']],
 [['Email and support','ایمیل و پشتیبانی'],['Account emails are sent through the configured Gmail SMTP sender. Password reset tokens are hashed, expire after 30 minutes and work once. Contact form messages are encrypted in the internal inbox. Cloudflare Turnstile receives the information needed for its anti-bot challenge. Do not include passwords or provider keys in support requests.','ایمیل حساب از فرستندهٔ SMTP جیمیل تنظیم‌شده ارسال می‌شود. توکن بازیابی هش‌شده، یک‌بارمصرف و دارای اعتبار ۳۰ دقیقه است. پیام تماس در صندوق داخلی رمزگذاری می‌شود. Cloudflare Turnstile اطلاعات لازم برای چالش ضدربات را دریافت می‌کند. گذرواژه یا کلید ارائه‌دهنده را در درخواست پشتیبانی ننویسید.']],
 [['Your controls','کنترل داده‌ها'],['Delete chats and projects locally, revoke shares and remove provider credentials at any time. Account deletion removes server account data and this device’s local database. Exported files and copies on other devices remain under your control. Optional analytics expires after 90 days and can be disabled from Cookie settings.','هر زمان می‌توانید چت و پروژه را محلی حذف کنید، اشتراک را لغو کنید و کلید ارائه‌دهنده را بردارید. حذف حساب، دادهٔ حساب در سرور و دیتابیس محلی این دستگاه را پاک می‌کند. فایل خروجی و نسخهٔ دستگاه‌های دیگر در اختیار خود شما باقی می‌ماند. آمار اختیاری پس از ۹۰ روز پاک می‌شود و از تنظیمات کوکی قابل غیرفعال کردن است.']],
];
const terms=[
 [['Your account','حساب شما'],['Use a unique password and keep your provider keys private. You authorize this site to use connected keys for requests from your account. Provider charges, model access and usage limits follow that provider’s terms.','از گذرواژهٔ منحصربه‌فرد استفاده کنید و کلید ارائه‌دهنده را خصوصی نگه دارید. با اتصال کلید، استفاده از آن برای درخواست‌های حساب خودتان را مجاز می‌کنید. هزینه، دسترسی مدل و محدودیت مصرف تابع شرایط ارائه‌دهنده است.']],
 [['Content and results','محتوا و نتیجه'],['Upload only material you have the right to use. AI responses may be incomplete or wrong. Review important decisions, generated code and professional information before acting or publishing. Images and sources retain their original licenses.','فقط محتوایی را بارگذاری کنید که حق استفاده از آن را دارید. پاسخ هوش مصنوعی می‌تواند ناقص یا اشتباه باشد. تصمیم مهم، کد تولیدشده و اطلاعات تخصصی را پیش از استفاده یا انتشار بررسی کنید. عکس و منبع تابع مجوز اصلی خود است.']],
 [['Acceptable use','استفادهٔ مجاز'],['Do not bypass access controls, access another user’s records, extract secrets, distribute malware or abuse APIs. Excessive or suspicious requests may be limited or blocked.','دور زدن کنترل دسترسی، خواندن رکورد دیگران، استخراج اسرار، انتشار بدافزار و سوءاستفاده از API مجاز نیست. درخواست بیش از حد یا مشکوک ممکن است محدود یا مسدود شود.']],
 [['Availability and your database','دسترسی و دیتابیس شما'],['Models and web search depend on third-party services and internet access. Private chats are stored on your device; you are responsible for exporting important data before clearing browser storage. Continuous, error-free availability is not guaranteed.','مدل و جست‌وجوی وب به سرویس‌های بیرونی و اینترنت وابسته است. چت خصوصی روی دستگاه شماست؛ پیش از پاک کردن حافظهٔ مرورگر از اطلاعات مهم خروجی بگیرید. دسترسی دائمی و بی‌خطا تضمین نمی‌شود.']],
 [['Changes and support','تغییرات و پشتیبانی'],['Features and these terms may be updated. The date on this page identifies the latest revision. For questions, contact pimxagent@gmail.com or use our contact form.','امکانات و شرایط ممکن است به‌روزرسانی شوند. تاریخ این صفحه آخرین تغییر را مشخص می‌کند. برای پرسش با pimxagent@gmail.com یا فرم تماس ارتباط بگیرید.']],
];
export async function LegalPage({kind}:{kind:'privacy'|'terms'}){const locale=await getLocale(),i=locale==='fa'?1:0,rows=kind==='privacy'?privacy:terms;return <SiteFrame><article className="prose-page"><span className="site-eyebrow">{i?'به‌روزرسانی: ۲۷ سپتامبر ۲۰۲۶':'UPDATED SEPTEMBER 27, 2026'}</span><h1>{kind==='privacy'?(i?'اطلاعات شما چگونه استفاده می‌شود؟':'Your data, explained.'):(i?'شرایط استفاده از PIMX Agent':'Terms of use')}</h1><p>{i?'با استفاده از سایت، شرایط و روش حفظ حریم خصوصی را بپذیرید و دادهٔ مهم را روی دستگاه خودتان حفظ کنید.':'Understand how your workspace works and keep a copy of the data that matters to you.'}</p>{rows.map((row,index)=><section key={index}><h2>{row[0][i]}</h2><p>{row[1][i]}</p></section>)}<p><Link href={localizedHref('/account',locale)}>{i?'حساب و انتقال دیتابیس':'Account & database transfer'}</Link> · <Link href={localizedHref('/contact',locale)}>{i?'تماس با ما':'Contact us'}</Link> · <a href="mailto:pimxagent@gmail.com">pimxagent@gmail.com</a></p></article></SiteFrame>;}
