'use client';
import Link from 'next/link';
import Image from 'next/image';
import { useRef, useState } from 'react';
import { motion, useScroll, useTransform, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, Play, Pause, Globe2, Code2, Presentation, Telescope, BookOpen, GraduationCap, Swords, Columns2, Network, ShieldCheck, HardDriveDownload, Sparkles, ChevronDown } from 'lucide-react';
import { SiteFrame } from './SiteFrame';
import { ProductStage } from './ProductStage';
import { useLocale } from '@/components/i18n/LocaleProvider';
import { localizedHref } from '@/lib/i18n/text';

const capabilities=[
  {icon:Telescope,name:['Deep Research','تحقیق عمیق'],desc:['From a question to a grounded report. Search, read, cross-check and synthesize.','از یک سؤال تا گزارشی مستند؛ جست‌وجو، مطالعه، بررسی شواهد و جمع‌بندی.']},
  {icon:Code2,name:['Web Development','ساخت وب'],desc:['Build real websites. Edit the files, interact with the preview and take the ZIP.','وب‌سایت واقعی بسازید؛ فایل‌ها را ویرایش کنید، پیش‌نمایش را اجرا کنید و ZIP بگیرید.']},
  {icon:Presentation,name:['Slide Studio','استودیوی اسلاید'],desc:['A complete story, beautifully presented. Images, layouts, notes, PPTX and PDF.','روایتی کامل با طراحی زیبا؛ عکس، چیدمان، یادداشت و خروجی PowerPoint و PDF.']},
  {icon:BookOpen,name:['Sources','منابع'],desc:['Bring your documents. Get answers connected to the passages that matter.','اسناد خودتان را بیاورید و پاسخ مرتبط با بخش‌های مهم آن‌ها بگیرید.']},
  {icon:GraduationCap,name:['Learn','یادگیری'],desc:['Learn by doing. Roadmaps, Socratic dialogue and interactive recall cards.','با انجام دادن یاد بگیرید؛ مسیر آموزشی، گفتگوی سقراطی و کارت‌های مرور تعاملی.']},
  {icon:Swords,name:['Debate','مناظره'],desc:['Test an idea against opposing views before settling on a conclusion.','پیش از نتیجه‌گیری، ایده را از دیدگاه‌های مخالف بررسی کنید.']},
  {icon:Columns2,name:['Compare Models','مقایسهٔ مدل‌ها'],desc:['One prompt, up to four models. See their responses side by side.','یک درخواست برای یک تا چهار مدل؛ پاسخ‌ها را کنار هم ببینید.']},
  {icon:Network,name:['Model Council','شورای مدل‌ها'],desc:['Different perspectives, a shared outcome. Models brainstorm and synthesize.','دیدگاه‌های گوناگون و یک نتیجهٔ مشترک؛ همفکری و جمع‌بندی مدل‌ها.']},
];
export function Welcome(){
  const locale=useLocale(),fa=locale==='fa',index=fa?1:0,copy=(en:string,faText:string)=>fa?faText:en,href=(path:string)=>localizedHref(path,locale);
  const [mode,setMode]=useState(0),[playing,setPlaying]=useState(false),video=useRef<HTMLVideoElement>(null),stage=useRef<HTMLElement>(null),reduced=useReducedMotion();
  const {scrollYProgress}=useScroll({target:stage,offset:['start end','end start']}),tilt=useTransform(scrollYProgress,[0,.5,1],[12,0,-12]);
  const steps=[{label:['Research','تحقیق'],icon:Globe2,title:['Find the signal.','شواهد را پیدا کنید.'],desc:['Ask a focused question. Follow the evidence through planning, live web search and a sourced report.','یک سؤال مشخص بپرسید. مسیر شواهد را از برنامه‌ریزی و جست‌وجوی وب تا گزارش مستند دنبال کنید.']},{label:['Build','ساخت'],icon:Code2,title:['Make it real.','ایده را واقعی کنید.'],desc:['Turn an idea into files you can run. Refine the code and download your complete project.','ایده را به فایل‌های قابل اجرا تبدیل کنید، کد را بهتر کنید و پروژهٔ کامل را دریافت کنید.']},{label:['Present','ارائه'],icon:Presentation,title:['Give ideas a stage.','ایده‌ها را به صحنه بیاورید.'],desc:['Shape your story with images and thoughtful layouts. Present it here or export to PowerPoint and PDF.','روایت را با عکس و چیدمان مناسب بسازید؛ همین‌جا ارائه کنید یا PowerPoint و PDF بگیرید.']}];
  return <SiteFrame><div className="kinetic-home">
    <section className="cosmic-hero" aria-labelledby="hero-title"><div className="hero-stardust" aria-hidden/><div className="hero-copy"><span className="cosmic-eyebrow"><i/>{copy('YOUR IDEAS. THEIR NEXT CHAPTER.','ایده‌های شما. فصل بعدی آن‌ها.')}</span><h1 id="hero-title">{copy('Ideas deserve','ایده‌ها فراتر از')}<br/>{copy('more than','یک گفتگو')}<br/><em>{copy('a chat.','ارزش دارند.')}</em></h1><p>{copy('Research. Build. Present. One intelligent workspace that moves your ideas forward — with the models you choose.','تحقیق کنید، بسازید، ارائه کنید. یک فضای کاری هوشمند که ایده‌ها را با مدل‌های منتخب شما به نتیجه می‌رساند.')}</p><div className="hero-actions"><Link href={href('/signup')} className="site-button hero-cta">{copy('Create your workspace','فضای کاری‌تان را بسازید')}<ArrowUpRight size={20}/></Link><a href="#the-workspace" className="hero-discover">{copy('Explore the possibilities','امکانات را ببینید')}<ChevronDown size={16}/></a></div><div className="hero-trust"><span><ShieldCheck size={14}/>{copy('Your keys, protected','کلیدهای شما، محافظت‌شده')}</span><span><HardDriveDownload size={14}/>{copy('Your chats, on your device','چت‌های شما، روی دستگاه شما')}</span></div></div>
      <div className="hero-universe"><ProductStage/></div>
      <div className="hero-bottom"><span>{copy('A little curiosity. Unlimited possibilities.','کمی کنجکاوی. امکانات بی‌پایان.')}</span><a href="#the-workspace" aria-label={copy('Scroll to workspace','رفتن به بخش فضای کاری')}><ArrowRight size={18}/></a></div>
    </section>
    <div className="capability-marquee" aria-hidden="true"><div>{Array.from({length:2},(_,i)=><span key={i}>{copy('DEEP RESEARCH','تحقیق عمیق')} <b>✦</b> {copy('WEB DEV','ساخت وب')} <b>✦</b> {copy('SLIDE STUDIO','استودیوی اسلاید')} <b>✦</b> {copy('MODEL COUNCIL','شورای مدل‌ها')} <b>✦</b> {copy('THINK BIGGER','بزرگ‌تر فکر کنید')} <b>✦</b> </span>)}</div></div>
    <section id="the-workspace" className="workspace-story" ref={stage}><div className="section-intro"><span className="cosmic-eyebrow">{copy('ONE WORKSPACE. MANY POSSIBILITIES.','یک فضای کاری. مسیرهای گوناگون.')}</span><h2>{copy('From your first spark','از اولین جرقه')}<br/><em>{copy('to something extraordinary.','تا یک نتیجهٔ فوق‌العاده.')}</em></h2><p>{copy('Follow the work as it happens. Plan, search, create and refine without losing your train of thought.','روند انجام کار را ببینید. برنامه‌ریزی کنید، جست‌وجو کنید، بسازید و بهترش کنید؛ بدون از دست دادن مسیر فکرتان.')}</p></div><div className="mode-tabs" role="tablist" aria-label={copy('Explore workflows','دیدن مسیرهای کاری')}>{steps.map((step,i)=><button role="tab" key={i} aria-selected={mode===i} aria-controls="workflow-preview" id={`workflow-tab-${i}`} onClick={()=>setMode(i)}><step.icon size={18}/>{step.label[index]}<span>0{i+1}</span></button>)}</div>
      <motion.div id="workflow-preview" role="tabpanel" aria-labelledby={`workflow-tab-${mode}`} className="workflow-stage" style={{rotateX:reduced?0:tilt,transformPerspective:1400}}><div className="workflow-visual"><Image src="/media/studio-portal.webp" alt={copy('Violet glass creative studio with a chrome infinity sculpture','استودیوی خلاقیت شیشه‌ای بنفش با مجسمهٔ بی‌نهایت کرومی')} width={1536} height={864}/><div className="workflow-number">0{mode+1}</div><div className="workflow-orbit"><i/><i/><i/></div></div><motion.div className="workflow-content" key={mode} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><span className="cosmic-eyebrow">{steps[mode].label[index]}</span><h3>{steps[mode].title[index]}</h3><p>{steps[mode].desc[index]}</p><ol>{(mode===0?[copy('Understand the goal','شناخت هدف'),copy('Search and read sources','جست‌وجو و مطالعهٔ منابع'),copy('Synthesize a grounded report','ساخت گزارش مستند')]:mode===1?[copy('Describe what you need','شرح چیزی که می‌خواهید'),copy('Generate and run real files','ساخت و اجرای فایل‌های واقعی'),copy('Refine and download the project','ویرایش و دریافت پروژه')]:[copy('Define audience and story','تعریف مخاطب و روایت'),copy('Choose images and layouts','انتخاب عکس و چیدمان'),copy('Present or export','ارائه یا دریافت خروجی')]).map((step,i)=><li key={i}><span>0{i+1}</span>{step}<ArrowUpRight size={15}/></li>)}</ol><Link href={href('/signup')} className="text-link">{copy('Make your first project','اولین پروژه‌تان را بسازید')}<ArrowUpRight size={16}/></Link></motion.div></motion.div>
    </section>
    <section className="possibilities-section"><div className="section-intro inline"><div><span className="cosmic-eyebrow">{copy('BUILT FOR THE WAY YOU THINK.','برای شیوهٔ فکر کردن شما.')}</span><h2>{copy('Your next move?','قدم بعدی شما؟')}<br/><em>{copy('Make it anything.','هر چیزی می‌تواند باشد.')}</em></h2></div><p>{copy('Switch perspectives, learn something new or build something worth sharing. Your workspace adapts to the job.','دیدگاه‌ها را عوض کنید، چیز تازه‌ای یاد بگیرید یا چیزی بسازید که ارزش اشتراک‌گذاری دارد. فضای کاری با نوع کار شما هماهنگ می‌شود.')}</p></div><div className="capability-grid">{capabilities.map((item,i)=><motion.a href={href('/signup')} className="capability-card" key={i} initial={{opacity:0,y:28,rotateX:8}} whileInView={{opacity:1,y:0,rotateX:0}} viewport={{once:true,amount:.2}} transition={{duration:.5,delay:i%4*.07}} whileHover={reduced?{}:{y:-7,rotateY:3}}><div className="capability-card-top"><div className={`capability-glyph glyph-${i}`}><item.icon size={25}/></div><span>0{i+1}</span></div><h3>{item.name[index]}</h3><p>{item.desc[index]}</p><ArrowUpRight className="capability-arrow" size={18}/></motion.a>)}</div></section>
    <section className="film-section"><div className="film-caption"><span className="cosmic-eyebrow">{copy('A LITTLE MOTION. A LOT OF POSSIBILITY.','کمی حرکت. دنیایی از امکان.')}</span><h2>{copy('Meet your creative orbit.','به مدار خلاقیت‌تان خوش آمدید.')}</h2></div><div className="film-screen"><video ref={video} src="/media/pimx-product-film.webm" poster="/media/pimx-workspace-dark.webp" muted loop playsInline preload="none" aria-label={copy('PIMX Agent orbital motion film','ویدیوی موشن مدار PIMX Agent')} onEnded={()=>setPlaying(false)}/><button className="film-play" onClick={async()=>{if(!video.current)return;if(playing){video.current.pause();setPlaying(false);}else{try{await video.current.play();setPlaying(true);}catch{setPlaying(false);}}}} aria-label={playing?copy('Pause film','توقف ویدیو'):copy('Play film','پخش ویدیو')}>{playing?<Pause size={22}/>:<Play size={22}/>}</button><div className="film-meta"><span>{copy('PIMX / IDEAS IN MOTION','PIMX / ایده‌ها در حرکت')}</span><span>{copy('Soundless. Made to inspire.','بی‌صدا. برای الهام بخشیدن.')}</span></div></div></section>
    <section className="local-first-section"><div className="database-sculpture" aria-hidden><div className="database-disc"/><div className="database-disc"/><div className="database-disc"/><div className="database-core">✦</div><span className="sculpture-ring"/></div><div><span className="cosmic-eyebrow">{copy('YOUR WORK. YOUR DEVICE.','کار شما. دستگاه شما.')}</span><h2>{copy('A workspace that','فضایی که')}<br/><em>{copy('stays yours.','مال خودتان می‌ماند.')}</em></h2><p>{copy('Your private conversations stay encrypted in your browser. Export your entire chat database with a passphrase, bring it to another device and pick up exactly where you left off.','گفتگوهای خصوصی در مرورگر خودتان رمزگذاری می‌شوند. کل پایگاه دادهٔ چت را با یک گذرواژه خروجی بگیرید، روی دستگاه دیگری وارد کنید و از همان‌جا ادامه دهید.')}</p><div className="privacy-points"><span><ShieldCheck size={18}/>{copy('Server-side key vault','مخزن کلید سمت سرور')}</span><span><HardDriveDownload size={18}/>{copy('Encrypted export & import','خروجی و ورود رمزگذاری‌شده')}</span><span><Globe2 size={18}/>{copy('Web + installable PWA','وب و PWA قابل نصب')}</span></div><Link href={href('/privacy')} className="text-link">{copy('Read our privacy approach','روش حفظ حریم خصوصی را ببینید')}<ArrowUpRight size={16}/></Link></div></section>
    <section className="final-invitation"><div className="invitation-desk" aria-hidden/><span className="cosmic-eyebrow">{copy('THE NEXT CHAPTER STARTS HERE.','فصل بعدی از همین‌جا شروع می‌شود.')}</span><h2>{copy('What will you','قرار است چه چیزی')}<br/><em>{copy('make possible?','را ممکن کنید؟')}</em></h2><Link href={href('/signup')} className="site-button hero-cta">{copy('Start creating','شروع به ساختن کنید')}<ArrowUpRight size={20}/></Link><p>{copy('Your models. Your ideas. Your workspace.','مدل‌های شما. ایده‌های شما. فضای کاری شما.')}</p></section>
    <Link href={href('/signup')} className="mobile-cta">{copy('Create your workspace','ساخت فضای کاری')}<ArrowUpRight size={18}/></Link>
  </div></SiteFrame>;
}
