'use client';
import Link from 'next/link';
import { useRef, useState } from 'react';
import { motion, useScroll, useTransform, useReducedMotion } from 'motion/react';
import { ArrowUpRight, ArrowRight, Play, Pause, Globe2, Code2, Presentation, Telescope, BookOpen, GraduationCap, Swords, Columns2, Network, ShieldCheck, HardDriveDownload, Sparkles, ChevronDown, Check, FileText } from 'lucide-react';
import { SiteFrame } from './SiteFrame';
import { ProductStage } from './ProductStage';
import { useLocale } from '@/components/i18n/LocaleProvider';
import { localizedHref } from '@/lib/i18n/text';

const capabilities=[
  {icon:Telescope,name:['Deep Research','تحقیق عمیق'],desc:['From a question to a grounded report. Search, read, cross-check and synthesize.','از یک سؤال تا گزارشی مستند؛ جست‌وجو، مطالعه، بررسی شواهد و جمع‌بندی.']},
  {icon:Code2,name:['Web Development','ساخت وب'],desc:['Build real websites. Edit the files, interact with the preview and take the ZIP.','وب‌سایت واقعی بسازید؛ فایل‌ها را ویرایش کنید، پیش‌نمایش را اجرا کنید و ZIP بگیرید.']},
  {icon:Presentation,name:['Slide Studio','استودیوی اسلاید'],desc:['A complete story, beautifully presented. Images, layouts, notes, PPTX and PDF.','روایتی کامل با طراحی زیبا؛ عکس، چیدمان، یادداشت و خروجی PowerPoint و PDF.']},
  {icon:BookOpen,name:['Sources','منابع'],desc:['Bring your documents. Get answers connected to the passages that matter.','اسناد خودتان را بیاورید و پاسخ مرتبط با بخش‌های مهم آن‌ها بگیرید.']},
  {icon:GraduationCap,name:['Learn','یادگیری'],desc:['Learn by doing. Roadmaps, Socratic dialogue and interactive recall cards.','با انجام دادن یاد بگیرید؛ مسیر آموزشی، گفتگوی سقراطی و کارت‌های مرور تعاملی.']},
  {icon:Swords,name:['Debate','مناظره'],desc:['Test an idea against opposing views before settling on a conclusion.','پیش از نتیجه‌گیری، ایده را از دیدگاه‌های مخالف بررسی کنید.']},
  {icon:Columns2,name:['Compare Models','مقایسهٔ مدل‌ها'],desc:['One prompt, up to four models. See their responses side by side.','یک درخواست برای یک تا چهار مدل؛ پاسخ‌ها را کنار هم ببینید.']},
  {icon:Network,name:['Model Council','شورای مدل‌ها'],desc:['Different perspectives, a shared outcome. Models brainstorm and synthesize.','دیدگاه‌های گوناگون و یک نتیجهٔ مشترک؛ همفکری و جمع‌بندی مدل‌ها.']},
];
const examples=[['“Research the future of solar energy.”','«دربارهٔ آیندهٔ انرژی خورشیدی تحقیق کن.»'],['“Build a website for my photography.”','«برای نمونه‌کارهای عکاسی‌ام سایت بساز.»'],['“Make a presentation for my next pitch.”','«برای معرفی ایده‌ام ارائه بساز.»'],['“Explain this PDF in plain language.”','«این PDF را ساده برایم توضیح بده.»'],['“Teach me Python, step by step.”','«پایتون را قدم‌به‌قدم یادم بده.»'],['“Challenge my business idea.”','«ایدهٔ کسب‌وکارم را نقد کن.»'],['“How do these models answer this?”','«جواب این مدل‌ها چه فرقی دارد؟»'],['“Let the models think together.”','«بگذار مدل‌ها با هم فکر کنند.»']];
function WorkflowDemo({mode,fa}:{mode:number;fa:boolean}){const c=(en:string,persian:string)=>fa?persian:en;return <div className={'workflow-demo demo-'+mode}><div className="demo-chrome"><span className="demo-dots"><i/><i/><i/></span><span>PIMX / {['RESEARCH','WEB STUDIO','SLIDE STUDIO'][mode]}</span><span className="demo-live"><i/>{c("Example","نمونه")}</span></div><div className="demo-prompt"><Sparkles size={17}/><span>{[c("Research the future of solar energy","دربارهٔ آیندهٔ انرژی خورشیدی تحقیق کن"),c("Build a website for my photography","برای نمونه‌کارهای عکاسی‌ام سایت بساز"),c("Create a presentation about clean energy","دربارهٔ انرژی پاک یک ارائه بساز")][mode]}</span></div>{mode===0?<div className="research-demo"><div className="demo-progress"><span><Check size={13}/>{c("Plan","برنامه")}</span><span><Check size={13}/>{c("Search","جست‌وجو")}</span><span><FileText size={13}/>{c("Report","گزارش")}</span></div><div className="demo-report"><span className="demo-kicker">{c("RESEARCH BRIEF","خلاصهٔ تحقیق")}</span><h4>{c("A brighter energy future.","آینده‌ای روشن‌تر برای انرژی.")}</h4><p>{c("Solar power, storage and the next generation of energy systems.","انرژی خورشیدی، ذخیره‌سازی و نسل آیندهٔ سیستم‌های انرژی.")}</p><div className="demo-chart" aria-hidden>{[26,37,44,55,68,81,96].map((height,i)=><i key={i} style={{height:height+'%'}}/>)}</div><div className="demo-sources"><Globe2 size={14}/><span>{c("Sources connected to the report","منابع، کنار گزارش")}</span><ArrowUpRight size={14}/></div></div></div>:mode===1?<div className="web-demo"><div className="demo-files"><span><Code2 size={13}/> index.html</span><span>styles.css</span><span>app.js</span><pre><code>{'<main>\n  <h1>Light & stories.</h1>\n  <section class="gallery">\n    Your next perspective.\n  </section>\n</main>'}</code></pre></div><div className="demo-website"><span className="demo-site-brand">LUMA / STUDIO</span><h4>Light.<br/>Stories.<br/><em>Perspective.</em></h4><div className="demo-gallery"><i/><i/><i/></div><span className="demo-site-link">EXPLORE THE COLLECTION ↗</span></div><div className="demo-output"><span><Check size={13}/>{c("Interactive preview","پیش‌نمایش تعاملی")}</span><span><HardDriveDownload size={13}/> ZIP</span></div></div>:<div className="slides-demo"><div className="demo-slide"><span>01 / THE NEXT CHAPTER</span><h4>{c("Energy for","انرژی برای")}<br/><em>{c("a better tomorrow.","فردایی بهتر.")}</em></h4><div className="demo-sun"/><small>{c("Small ideas. Lasting change.","ایده‌های کوچک. تغییرهای ماندگار.")}</small></div><div className="demo-thumbnails">{['01','02','03','04'].map((n,i)=><span key={n}><i style={{width:(35+i*13)+'%'}}/>{n}</span>)}</div><div className="demo-output"><span><Presentation size={13}/>{c("Slides + speaker notes","اسلاید و یادداشت ارائه")}</span><span>PPTX · PDF</span></div></div>}</div>;}
export function Welcome(){
  const locale=useLocale(),fa=locale==='fa',index=fa?1:0,copy=(en:string,faText:string)=>fa?faText:en,href=(path:string)=>localizedHref(path,locale),chat='https://chat.pimxagent.pages.dev'+(fa?'/fa/':'/');
  const [mode,setMode]=useState(0),[playing,setPlaying]=useState(false),video=useRef<HTMLVideoElement>(null),stage=useRef<HTMLElement>(null),reduced=useReducedMotion();
  const {scrollYProgress}=useScroll({target:stage,offset:['start end','end start']}),tilt=useTransform(scrollYProgress,[0,.5,1],[12,0,-12]);
  const steps=[{label:['Research','تحقیق'],icon:Globe2,title:['Find the signal.','شواهد را پیدا کنید.'],desc:['Ask a focused question. Follow the evidence through planning, live web search and a sourced report.','یک سؤال مشخص بپرسید. مسیر شواهد را از برنامه‌ریزی و جست‌وجوی وب تا گزارش مستند دنبال کنید.']},{label:['Build','ساخت'],icon:Code2,title:['Make it real.','ایده را واقعی کنید.'],desc:['Turn an idea into files you can run. Refine the code and download your complete project.','ایده را به فایل‌های قابل اجرا تبدیل کنید، کد را بهتر کنید و پروژهٔ کامل را دریافت کنید.']},{label:['Present','ارائه'],icon:Presentation,title:['Give ideas a stage.','ایده‌ها را به صحنه بیاورید.'],desc:['Shape your story with images and thoughtful layouts. Present it here or export to PowerPoint and PDF.','روایت را با عکس و چیدمان مناسب بسازید؛ همین‌جا ارائه کنید یا PowerPoint و PDF بگیرید.']}];
  return <SiteFrame><div className="kinetic-home">
    <section className="cosmic-hero" aria-labelledby="hero-title"><div className="hero-stardust" aria-hidden/><div className="hero-copy"><span className="cosmic-eyebrow"><i/>{copy("PIMX AGENT · YOUR AI WORKSPACE","PIMX AGENT · فضای کاری هوش مصنوعی شما")}</span><h1 id="hero-title">{copy("Ask it.","بپرس.")}<br/>{copy("Imagine it.","تصورش کن.")}<br/><em>{copy("Make it real.","واقعی‌اش کن.")}</em></h1><p>{copy("PIMX Agent brings AI chat and practical tools together. Ask a question, research a topic, build a website or create a presentation — all in one place, with the model you choose.","PIMX Agent یک فضای کاری با هوش مصنوعی است. سؤال بپرس، دربارهٔ موضوعی تحقیق کن، سایت بساز یا ارائه آماده کن؛ همه در یک جا، با مدلی که خودت انتخاب می‌کنی.")}</p><div className="hero-actions"><Link href={chat} className="site-button hero-cta">{copy("Continue without login","ادامه بدون لاگین")}<ArrowUpRight size={20}/></Link><a href="#the-workspace" className="hero-discover">{copy('Explore the possibilities','امکانات را ببینید')}<ChevronDown size={16}/></a></div><div className="hero-trust"><span><ShieldCheck size={14}/>{copy("No signup. No password.","بدون ثبت‌نام و رمز عبور")}</span><span><HardDriveDownload size={14}/>{copy('Your chats, on your device','چت‌های شما، روی دستگاه شما')}</span></div></div>
      <div className="hero-universe"><ProductStage/></div>
      <div className="hero-bottom"><span>{copy("One prompt. So many ways forward.","یک درخواست. راه‌های زیادی برای ادامه.")}</span><a href="#the-workspace" aria-label={copy('Scroll to workspace','رفتن به بخش فضای کاری')}><ArrowRight size={18}/></a></div>
    </section>
    <div className="capability-marquee" aria-hidden="true"><div className="marquee-track">{[0,1].map(group=><div className="marquee-group" key={group}>{[...capabilities,...capabilities].map((item,i)=><span key={i}>{item.name[index]}<b>✦</b></span>)}</div>)}</div></div>
    <section id="the-workspace" className="workspace-story" ref={stage}><div className="section-intro"><span className="cosmic-eyebrow">{copy("LESS EXPLAINING. MORE DOING.","از حرف به عمل.")}</span><h2>{copy("Tell it what you need.","بگو چه چیزی می‌خواهی.")}<br/><em>{copy("Watch your idea take shape.","شکل گرفتنش را ببین.")}</em></h2><p>{copy("It goes beyond answering. Your conversation and the work it produces sit side by side. Explore these examples of what you can make.","فقط پاسخ نمی‌گیری. گفتگو در یک سمت و نتیجهٔ کار در سمت دیگر پیش می‌رود. این نمونه‌ها نشان می‌دهند چه چیزهایی می‌توانی بسازی.")}</p></div><div className="mode-tabs" role="tablist" aria-label={copy('Explore workflows','دیدن مسیرهای کاری')}>{steps.map((step,i)=><button role="tab" key={i} aria-selected={mode===i} aria-controls="workflow-preview" id={`workflow-tab-${i}`} onClick={()=>setMode(i)}><step.icon size={18}/>{step.label[index]}<span>0{i+1}</span></button>)}</div>
      <motion.div id="workflow-preview" role="tabpanel" aria-labelledby={`workflow-tab-${mode}`} className="workflow-stage" style={{rotateX:reduced?0:tilt,transformPerspective:1400}}><WorkflowDemo mode={mode} fa={fa}/><motion.div className="workflow-content" key={mode} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><span className="cosmic-eyebrow">{steps[mode].label[index]}</span><h3>{steps[mode].title[index]}</h3><p>{steps[mode].desc[index]}</p><ol>{(mode===0?[copy('Understand the goal','شناخت هدف'),copy('Search and read sources','جست‌وجو و مطالعهٔ منابع'),copy('Synthesize a grounded report','ساخت گزارش مستند')]:mode===1?[copy('Describe what you need','شرح چیزی که می‌خواهید'),copy('Generate and run real files','ساخت و اجرای فایل‌های واقعی'),copy('Refine and download the project','ویرایش و دریافت پروژه')]:[copy('Define audience and story','تعریف مخاطب و روایت'),copy('Choose images and layouts','انتخاب عکس و چیدمان'),copy('Present or export','ارائه یا دریافت خروجی')]).map((step,i)=><li key={i}><span>0{i+1}</span>{step}<ArrowUpRight size={15}/></li>)}</ol><Link href={chat} className="text-link">{copy("Try it in the workspace","در فضای کاری امتحانش کن")}<ArrowUpRight size={16}/></Link></motion.div></motion.div>
    </section>
    <section className="possibilities-section"><div className="section-intro inline"><div><span className="cosmic-eyebrow">{copy("A TOOL FOR EVERY NEXT STEP.","برای هر قدم، یک ابزار.")}</span><h2>{copy("One space.","یک فضا.")}<br/><em>{copy("Your whole creative process.","تمام مسیر خلق کردن.")}</em></h2></div><p>{copy('Switch perspectives, learn something new or build something worth sharing. Your workspace adapts to the job.','دیدگاه‌ها را عوض کنید، چیز تازه‌ای یاد بگیرید یا چیزی بسازید که ارزش اشتراک‌گذاری دارد. فضای کاری با نوع کار شما هماهنگ می‌شود.')}</p></div><div className="capability-grid">{capabilities.map((item,i)=><motion.a href={chat} className="capability-card" key={i} initial={{opacity:0,y:28,rotateX:8}} whileInView={{opacity:1,y:0,rotateX:0}} viewport={{once:true,amount:.2}} transition={{duration:.5,delay:i%4*.07}} whileHover={reduced?{}:{y:-7,rotateY:3}}><div className="capability-card-top"><div className={`capability-glyph glyph-${i}`}><item.icon size={25}/></div><span>0{i+1}</span></div><h3>{item.name[index]}</h3><p>{item.desc[index]}</p><span className="capability-example">{examples[i][index]}</span><ArrowUpRight className="capability-arrow" size={18}/></motion.a>)}</div></section>
    <section className="start-section"><div className="section-intro"><span className="cosmic-eyebrow">{copy("STRAIGHT TO THE GOOD PART.","مستقیم برو سراغ کار اصلی.")}</span><h2>{copy("Ready in three simple steps.","شروع، در سه قدم ساده.")}</h2><p>{copy("Every tool is open without an account. Pick your model once, then follow your curiosity.","همهٔ ابزارها بدون حساب در دسترس‌اند. یک بار مدل را انتخاب کن و بعد مسیر ایده‌ات را ادامه بده.")}</p></div><div className="start-grid">{[[copy("Open the chat","چت را باز کن"),copy("No forms, emails or passwords. Your workspace opens right away.","بدون فرم، ایمیل یا رمز عبور؛ فضای کاری مستقیم باز می‌شود.")],[copy("Connect your model","مدلت را وصل کن"),copy("Choose a provider and add its API key in Settings. Use the models available to you.","از تنظیمات، ارائه‌دهنده و کلید API خودت را اضافه کن و مدل دلخواه را انتخاب کن.")],[copy("Tell it your goal","خواسته‌ات را بنویس"),copy("Chat naturally or choose a tool. Refine the result, save it and take the output with you.","طبیعی گفتگو کن یا ابزار را انتخاب کن. نتیجه را بهتر کن، ذخیره کن و خروجی بگیر.")]].map((item,i)=><article key={i}><span className="start-number">0{i+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div><a href={chat} className="text-link">{copy('Open the chat — no account needed',"چت را باز کن، بدون نیاز به حساب")}<ArrowUpRight size={17}/></a></section>
    <section className="film-section"><div className="film-caption"><span className="cosmic-eyebrow">{copy('A LITTLE MOTION. A LOT OF POSSIBILITY.','کمی حرکت. دنیایی از امکان.')}</span><h2>{copy('Meet your creative orbit.','به مدار خلاقیت‌تان خوش آمدید.')}</h2></div><div className="film-screen"><video ref={video} src="/media/pimx-product-film.webm" poster="/media/pimx-workspace-dark.webp" muted loop playsInline preload="none" aria-label={copy('PIMX Agent orbital motion film','ویدیوی موشن مدار PIMX Agent')} onEnded={()=>setPlaying(false)}/><button className="film-play" onClick={async()=>{if(!video.current)return;if(playing){video.current.pause();setPlaying(false);}else{try{await video.current.play();setPlaying(true);}catch{setPlaying(false);}}}} aria-label={playing?copy('Pause film','توقف ویدیو'):copy('Play film','پخش ویدیو')}>{playing?<Pause size={22}/>:<Play size={22}/>}</button><div className="film-meta"><span>{copy('PIMX / IDEAS IN MOTION','PIMX / ایده‌ها در حرکت')}</span><span>{copy('Soundless. Made to inspire.','بی‌صدا. برای الهام بخشیدن.')}</span></div></div></section>
    <section className="local-first-section"><div className="database-sculpture" aria-hidden><div className="database-disc"/><div className="database-disc"/><div className="database-disc"/><div className="database-core">✦</div><span className="sculpture-ring"/></div><div><span className="cosmic-eyebrow">{copy("NO ACCOUNT. STILL YOUR SPACE.","بدون حساب؛ همچنان فضای خودت.")}</span><h2>{copy('A workspace that','فضایی که')}<br/><em>{copy('stays yours.','مال خودتان می‌ماند.')}</em></h2><p>{copy('Your private conversations stay encrypted in your browser. Export your entire chat database with a passphrase, bring it to another device and pick up exactly where you left off.','گفتگوهای خصوصی در مرورگر خودتان رمزگذاری می‌شوند. کل پایگاه دادهٔ چت را با یک گذرواژه خروجی بگیرید، روی دستگاه دیگری وارد کنید و از همان‌جا ادامه دهید.')}</p><div className="privacy-points"><span><ShieldCheck size={18}/>{copy('Server-side key vault','مخزن کلید سمت سرور')}</span><span><HardDriveDownload size={18}/>{copy('Encrypted export & import','خروجی و ورود رمزگذاری‌شده')}</span><span><Globe2 size={18}/>{copy('Web + installable PWA','وب و PWA قابل نصب')}</span></div><Link href={href('/privacy')} className="text-link">{copy('Read our privacy approach','روش حفظ حریم خصوصی را ببینید')}<ArrowUpRight size={16}/></Link></div></section>
    <section className="faq-section"><div className="section-intro"><span className="cosmic-eyebrow">{copy("A FEW THINGS TO KNOW.","چند نکته، قبل از شروع.")}</span><h2>{copy("Clear answers.","جواب‌های روشن.")}</h2></div><div className="faq-list">{[
 [copy("What exactly is PIMX Agent?","PIMX Agent دقیقاً چیست؟"),copy("A browser workspace that puts your chosen AI model next to the tools you need. Use it for everyday questions, research, working with documents, building websites, making slides and learning.","یک فضای کاری در مرورگر که مدل هوش مصنوعی انتخابی تو را کنار ابزارهای کاربردی قرار می‌دهد؛ برای سؤال‌های روزمره، تحقیق، کار با اسناد، ساخت سایت، اسلاید و یادگیری.")],
 [copy("Do I need to sign up?","باید ثبت‌نام کنم؟"),copy("No. There are no accounts, login screens or membership tiers. The same tools are available to everyone.","نه. حساب، صفحهٔ ورود یا سطح عضویت وجود ندارد. همه به همان ابزارها دسترسی دارند.")],
 [copy("Is an AI model included for free?","مدل هوش مصنوعی هم رایگان است؟"),copy("PIMX opens without an account. To generate responses, connect a model provider using your own API key. Available models, charges and usage limits are set by that provider. PIMX does not add account-based feature limits.","خود فضای کاری بدون حساب باز می‌شود. برای تولید پاسخ، ارائه‌دهندهٔ مدل را با کلید API خودت وصل می‌کنی. مدل‌های در دسترس، هزینه و سقف مصرف را آن ارائه‌دهنده تعیین می‌کند؛ PIMX محدودیت امکانات بر اساس عضویت ندارد.")],
 [copy("Where are my chats saved?","چت‌ها کجا ذخیره می‌شوند؟"),copy("Encrypted in this browser, without automatic server backup. Before clearing cookies or browser data, export your chats from Save & transfer chats. Import the file on another device with your transfer passphrase.","رمزگذاری‌شده در همین مرورگر، بدون پشتیبان‌گیری خودکار روی سرور. قبل از پاک کردن کوکی یا دادهٔ مرورگر، از بخش ذخیره و انتقال چت‌ها خروجی بگیر. فایل را با گذرواژهٔ انتقال روی دستگاه دیگر وارد کن.")],
 [copy("Can I use it on my phone?","روی گوشی هم می‌توانم استفاده کنم؟"),copy("Yes. The workspace adapts to mobile and desktop, and can be installed as a PWA. Generating answers and online research require an internet connection.","بله. فضای کاری روی گوشی و کامپیوتر سازگار است و می‌توانی آن را به شکل PWA نصب کنی. تولید پاسخ و تحقیق آنلاین به اینترنت نیاز دارد.")]
 ].map(([question,answer],i)=><details key={i}><summary>{question}<ChevronDown size={18}/></summary><p>{answer}</p></details>)}</div></section>
    <section className="final-invitation"><div className="invitation-desk" aria-hidden/><span className="cosmic-eyebrow">{copy('THE NEXT CHAPTER STARTS HERE.','فصل بعدی از همین‌جا شروع می‌شود.')}</span><h2>{copy('What will you','قرار است چه چیزی')}<br/><em>{copy('make possible?','را ممکن کنید؟')}</em></h2><Link href={chat} className="site-button hero-cta">{copy("Start without login","بدون لاگین شروع کن")}<ArrowUpRight size={20}/></Link><p>{copy("No signup. Just you, your model and your next idea.","بدون ثبت‌نام. فقط تو، مدلت و ایدهٔ بعدی‌ات.")}</p></section>
    <Link href={chat} className="mobile-cta">{copy("Open chat · No login","ورود به چت · بدون لاگین")}<ArrowUpRight size={18}/></Link>
  </div></SiteFrame>;
}
