'use client';
import {useState} from 'react';
import {lockVault,deleteLocalVault} from '@/lib/client/vault';
import {useLocale} from '@/components/i18n/LocaleProvider';
import {authError} from '@/components/site/AuthForm';
import {ConfirmDialog} from '@/components/ui/ConfirmDialog';
export function AccountSettings({id}:{id:string}){const locale=useLocale(),fa=locale==='fa',c=(en:string,faText:string)=>fa?faText:en;const [pending,setPending]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[deleting,setDeleting]=useState(false),[password,setPassword]=useState('');const remove=async()=>{setDeleting(false);setPending(true);setError('');try{const response=await fetch('/api/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}),data=await response.json();if(!response.ok)throw new Error(data.error?.message);await deleteLocalVault(id);lockVault();window.location.assign(fa?'/fa':'/');}catch(error){setError(error instanceof Error?(fa?authError(error.message):error.message):c('Request failed.','درخواست انجام نشد.'));setPending(false);}};
return <section className="site-form"><span className="site-eyebrow">{c('ACCOUNT & SECURITY','حساب و امنیت')}</span><h1>{c('Keep your account protected','حساب‌تان را امن نگه دارید')}</h1><p>{c('Changing your password signs out every other session. Your local chat encryption key stays intact.','تغییر گذرواژه تمام نشست‌های دیگر را می‌بندد. کلید رمزگذاری چت محلی حفظ می‌شود.')}</p><form onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget);if(form.get('newPassword')!==form.get('confirmPassword')){setError(c('The passwords do not match.','گذرواژه‌ها یکسان نیستند.'));return;}setPending(true);setError('');setSuccess('');try{const response=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,newPassword:form.get('newPassword'),confirmPassword:form.get('confirmPassword'),locale})}),data=await response.json();if(!response.ok)throw new Error(data.error?.message);setSuccess(c('Password changed. Other sessions are signed out.','گذرواژه تغییر کرد. نشست‌های دیگر بسته شدند.')+(data.emailSent?c(' A security email has been sent.',' ایمیل امنیتی ارسال شد.'):c(' Email notification is pending sender configuration.',' اعلان ایمیلی به تنظیم فرستنده نیاز دارد.')));}catch(error){setError(fa?authError(error instanceof Error?error.message:'Network error.'):error instanceof Error?error.message:'Network error.');}finally{setPending(false);}}}>
<label>{c('Current password','گذرواژهٔ فعلی')}<input name="password" value={password} onChange={event=>setPassword(event.target.value)} type="password" autoComplete="current-password" minLength={12} maxLength={128} required dir="ltr"/></label><label>{c('New password','گذرواژهٔ جدید')}<input name="newPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required dir="ltr"/></label><label>{c('Repeat new password','تکرار گذرواژهٔ جدید')}<input name="confirmPassword" type="password" autoComplete="new-password" minLength={12} maxLength={128} required dir="ltr"/></label>{error&&<p role="alert" className="form-error">{error}</p>}{success&&<p role="status">{success}</p>}<button className="site-button" disabled={pending}>{pending?c('Updating…','در حال انجام…'):c('Change password','تغییر گذرواژه')}</button></form><button className="site-button secondary" disabled={pending||password.length<12} onClick={()=>setDeleting(true)}>{c('Delete account and data','حذف حساب و داده‌ها')}</button><small>{c('Enter your current password to enable account deletion.','برای فعال شدن حذف حساب، گذرواژهٔ فعلی را وارد کنید.')}</small>{deleting&&<ConfirmDialog title={c('Permanently delete your account?','حذف دائمی حساب؟')} description={c('This deletes your profile, API keys, sessions and shared links from the server, plus this device’s local chat database. Copies on other devices must be removed there. Export important chats first.','پروفایل، کلید API، نشست‌ها و لینک‌های اشتراک از سرور و دیتابیس چت این دستگاه حذف می‌شوند. نسخهٔ دستگاه‌های دیگر باید روی همان دستگاه پاک شود. ابتدا از چت‌های مهم خروجی بگیرید.')} onClose={()=>setDeleting(false)} onConfirm={()=>void remove()}/>}</section>;}
