'use client';
import {useEffect,useState} from 'react';
import {Download,Upload,Database,ShieldCheck} from 'lucide-react';
import {unlockVault,exportChatDatabase,readChatDatabase,importChatDatabase} from '@/lib/client/vault';
import {useLocale} from '@/components/i18n/LocaleProvider';
import {ConfirmDialog} from '@/components/ui/ConfirmDialog';
export function DatabaseTransfer({id}:{id:string}){const fa=useLocale()==='fa',c=(en:string,faText:string)=>fa?faText:en;const [ready,setReady]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[imported,setImported]=useState<Record<string,unknown>>();
 useEffect(()=>{let active=true;unlockVault(id).then(()=>{if(active)setReady(true);},()=>{if(active)setError(c('Your local workspace could not be unlocked.','فضای کاری محلی باز نشد.'));});return()=>{active=false;};},[id,fa]);
 return <section className="site-form database-transfer"><span className="site-eyebrow"><Database size={16}/>{c('YOUR DATABASE. YOUR DEVICE.','دیتابیس شما. دستگاه شما.')}</span><h2>{c('Take your workspace with you','فضای کاری‌تان را همراه ببرید')}</h2><p>{c('Export every saved chat, project, attachment and generated artifact. The file is encrypted with your transfer passphrase. Private chats are never backed up to our server.','از تمام چت‌های ذخیره‌شده، پروژه‌ها، پیوست‌ها و خروجی‌ها فایل بگیرید. فایل با گذرواژهٔ انتقال رمزگذاری می‌شود. چت خصوصی روی سرور پشتیبان‌گیری نمی‌شود.')}</p><form onSubmit={async event=>{event.preventDefault();const form=new FormData(event.currentTarget),action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value'),passphrase=String(form.get('passphrase')||'');setPending(true);setError('');setSuccess('');try{if(action==='export'){if(passphrase!==form.get('confirmPassphrase'))throw new Error(c('The passphrases do not match.','گذرواژه‌ها یکسان نیستند.'));const blob=await exportChatDatabase(passphrase),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`pimx-chat-database-${new Date().toISOString().slice(0,10)}.pimxdb`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setSuccess(c('Your encrypted database is ready. Keep the passphrase safe; we cannot recover it.','فایل رمزگذاری‌شده آماده است. گذرواژه را حفظ کنید؛ بازیابی آن ممکن نیست.'));}else{const file=form.get('database');if(!(file instanceof File)||!file.size)throw new Error(c('Choose your exported database file.','فایل خروجی دیتابیس را انتخاب کنید.'));setImported(await readChatDatabase(file,passphrase));}}catch(error){setError(error instanceof Error?c(error.message,localError(error.message)):c('Transfer failed.','انتقال انجام نشد.'));}finally{setPending(false);}}}>
 <label>{c('Transfer passphrase','گذرواژهٔ انتقال')}<input name="passphrase" type="password" minLength={12} maxLength={256} autoComplete="off" required dir="ltr"/></label><label>{c('Repeat passphrase for export','تکرار گذرواژه برای خروجی')}<input name="confirmPassphrase" type="password" minLength={12} maxLength={256} autoComplete="off" dir="ltr"/></label><label>{c('Database file to import','فایل دیتابیس برای ورود')}<input name="database" type="file" accept=".pimxdb,application/json"/></label><div className="transfer-actions"><button name="action" value="export" className="site-button" disabled={!ready||pending}><Download size={17}/>{pending?c('Processing…','در حال پردازش…'):c('Export chat database','خروجی دیتابیس چت')}</button><button name="action" value="import" className="site-button secondary" disabled={!ready||pending}><Upload size={17}/>{c('Upload chat database','آپلود دیتابیس چت')}</button></div></form><small><ShieldCheck size={14}/>{c('Processed on your device. API keys and session tokens are excluded. Sign in to the same account on the other device, then import this file.','پردازش روی دستگاه شماست. کلید API و توکن نشست در فایل قرار نمی‌گیرند. در دستگاه دیگر وارد همان حساب شوید و این فایل را وارد کنید.')}</small>{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}{imported&&<ConfirmDialog title={c('Replace this device’s workspace?','جایگزینی فضای کاری این دستگاه؟')} description={c(`The file contains ${(imported.chats as unknown[]).length} chats. This replaces the saved workspace on this device. Export your current database first if you need it.`,`این فایل ${(imported.chats as unknown[]).length} چت دارد و جای فضای کاری ذخیره‌شدهٔ این دستگاه را می‌گیرد. برای حفظ دادهٔ فعلی، ابتدا از آن خروجی بگیرید.`)} confirmLabel={c('Import database','ورود دیتابیس')} onClose={()=>setImported(undefined)} onConfirm={()=>{setPending(true);void importChatDatabase(imported).then(()=>window.location.assign(fa?'/fa/':'/'),()=>{setError(c('The database could not be saved. Your existing data is unchanged.','ذخیرهٔ دیتابیس انجام نشد. دادهٔ قبلی تغییری نکرده است.'));setPending(false);setImported(undefined);});}}/>}</section>;
}
function localError(message:string){const errors:Record<string,string>={'The passphrase is incorrect or the database file is invalid.':'گذرواژه نادرست است یا فایل دیتابیس معتبر نیست.','Use a transfer passphrase of 12 to 256 characters.':'گذرواژهٔ انتقال باید بین ۱۲ تا ۲۵۶ نویسه باشد.','This is not a compatible chat database.':'ساختار دیتابیس چت سازگار نیست.','The database file is too large.':'فایل دیتابیس بیش از حد بزرگ است.','The database exceeds the 100 MB transfer limit.':'دیتابیس از محدودیت ۱۰۰ مگابایت بیشتر است.'};return errors[message]||message;}
